<?php
/**
 * Storelocator template for store view
 *
 * @author Magento
 */

/**
 * @var $this MGS_Storelocator_Block_View
 * @see MGS_Storelocator_Block_View
 */
?>
<?php $_storeView = $this->helper('mgs_storelocator')->getStoreViewInstance(); ?>
<div class="row">
	<div class="col-md-5 col-sm-12 col-xs-12">
		 <?php if ($imageUrl = $_storeView->getStoreLogo()): ?>
			<div class="store-image">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'mgs_storelocator/'.$_storeView->getStoreLogo() ?>" alt="<?php echo $this->escapeHtml($_storeView->getName()) ?>" title="<?php echo $this->escapeHtml($_storeView->getName()) ?>" class="img-responsive"/>
			</div>
		<?php endif ?>
		<div class="store-info-detail">
			<div class="store-html-content store-information">
				<div class="title-block">
					<h4><?php echo $this->__('Store Information')?></h4>
				</div>
				<div class="content responsive-table">
				<table class="table portfolio-table table-hover">
				<tbody>
					<tr>
						<td><?php echo $this->__('Address:') ?></td>
						<td><?php echo $this->escapeHtml($_storeView->getStreetAddress()).' '.$this->escapeHtml(ucfirst($_storeView->getCity())).' '.$this->escapeHtml(ucfirst($_storeView->getState())).' '.$this->escapeHtml($_storeView->getZipcode()).' '.$_storeView->getCountry() ?></td>
					</tr>
					<?php if($_storeView->getPhone()): ?>
						<tr>
							<td><?php echo $this->__('Phone:') ?></td>
							<td><a href="tel:<?php echo $this->escapeHtml($_storeView->getPhone()) ?>"><?php echo $this->escapeHtml($_storeView->getPhone()) ?></a></td>
						</tr>
					<?php endif; ?>
					<?php if($_storeView->getEmail()): ?>
						<tr>
							<td><?php echo $this->__('Email:') ?></td>
							<td><a href="mailto:<?php echo $this->escapeHtml($_storeView->getEmail()) ?>"><?php echo $this->escapeHtml($_storeView->getEmail()) ?></a></td>
						</tr>
					<?php endif; ?>
					<?php if($_storeView->getFax()): ?>
						<tr>
							<td><?php echo $this->__('Fax:') ?></td>
							<td><?php echo $this->escapeHtml($_storeView->getFax()) ?></td>
						</tr>
					<?php endif; ?>
					<?php if($_storeView->getUrl()): ?>
						<tr>
							<td><?php echo $this->__('Website:') ?></td>
							<td><a target="_blank" href="<?php echo $_storeView->getUrl() ?>"><?php echo $_storeView->getUrl() ?></a></td>
						</tr>
					<?php endif; ?>
				</tbody>
				</table>
				</div>
			</div>
			<?php if($_storeView->getDescription()): ?>
				<div class="store-html-content store-description">
					<div class="title-block">
						<h4><?php echo $this->__('Store Description') ?></h4>
					</div>
					<div class="content">
						<?php echo $_storeView->getDescription(); ?>
					</div>
				</div>
			<?php endif ?>
			
			<?php if($_storeView->getTradingHours()): ?>
				<div class="store-html-content store-opening-hours">
					<div class="title-block">
						<h4><?php echo $this->__('Opening Hours') ?></h4>
					</div>
					<div class="content">
						<?php echo $_storeView->getTradingHours(); ?>
					</div>
				</div>
			<?php endif ?>
		</div>
	</div>
	<div class="col-md-7 col-sm-12 col-xs-12">
		<div id="map-detail"></div>
		<div class="back">
			<a href="<?php echo $this->getBackUrl() ?>"><i class="fa fa-angle-double-left" style="margin-right: 10px;"></i><?php echo $this->__('Back') ?></a>
		</div>
	</div>
</div>
<?php 
//Get store google map related information
$storeName = $_storeView->getName();
$storeLat = $_storeView->getLatitude();
$storeLong = $_storeView->getLongitude();
$storeRadius = $this->getRadius($_storeView);
?>
<?php if($storeLat && $storeLong): ?>
<script>
    //<![CDATA[
    var storeLat = <?php echo $storeLat ;?>;
    var storeLong = <?php echo $storeLong ;?>;
    var storeRadius = <?php echo $storeRadius ;?>;
    var storeInfoText = '<div class="map-short-info"><h3><?php echo $storeName ; ?></h3><p><?php echo $_storeView->getStreetAddress() ?> <?php echo $_storeView->getCity() ?> <?php echo $_storeView->getState() ?> <?php echo $_storeView->getZipcode() ?> <?php echo $_storeView->getCountry() ?></p>';
    var googleMapDivId = 'map-detail';
    google.maps.event.addDomListener(window, 'load', initialize(storeLat, storeLong, storeRadius, storeInfoText, googleMapDivId));
      //]]>
</script>
<?php endif ?>