<div class="edit-static-form">
	<form action="<?php echo $this->getUrl('mpanel/post/block') ?>" method="POST" enctype="multipart/form-data" id="block-form">
		
		<div class="row">
			<div class="col-md-12 builder-title">
				<h2><?php echo $this->__('Section Settings') ?></h2>
			</div>
		</div>
		<div class="form-horizontal">
		
			<div id="form_tabs" class="tabbable">
				<ul class="nav nav-tabs">
					<li class="active">
						<a href="#general" data-toggle="tab">
							<?php echo $this->__('General') ?>
						</a>
					</li>
					
					<li>
						<a href="#product" data-toggle="tab" id="product-tab-nav">
							<?php echo $this->__('Column Config') ?>
						</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="general">
						<div class="form-group">
							<label class="col-sm-4 control-label" for="fullwidth"><?php echo $this->__('Fullwidth') ?></label>
							<div class="col-sm-8">
								<select class="input-text" name="fullwidth" id="fullwidth">
									<option value="0"><?php echo $this->__('No') ?></option>
									<option value="1"<?php if($this->_block->getFullwidth()): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
					
						<div class="form-group">
							<input type="hidden" name="name" value="<?php echo $this->_block->getName() ?>"/>
							<input type="hidden" name="theme_name" value="<?php echo $this->_block->getThemeName() ?>"/>
							<input type="hidden" name="block_id" value="<?php echo $this->_block->getId() ?>"/>
							<input type="hidden" name="current_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl() ?>"/>
							
							<label class="col-sm-4 control-label" for="class_name"><?php echo $this->__('Class name') ?></label>
							<div class="col-sm-8">
								<input type="text" name="class" id="class_name" class="input-text" value="<?php echo $this->_block->getClass() ?>"/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="background"><?php echo $this->__('Background color') ?></label>
							<div class="col-sm-8">
								<input type="text" name="background" id="background" class="input-text" value="<?php echo $this->_block->getBackground() ?>"/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="background"><?php echo $this->__('Background image') ?></label>
							<div class="col-sm-8">
								
								<input type="file" name="background_image" id="background"/>
								<?php if($this->_block->getBackgroundImage()!=''): ?>
									<div class="image-temp">
										<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'mpanel/background/'.$this->_block->getBackgroundImage()?>" class="background-preview" alt=""/>
										<label for="remove_background">
											<input type="checkbox" name="remove_background" value="1" id="remove_background"/> <?php echo $this->__('Remove background') ?>
										</label>
									</div>
								<?php endif ?>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="background_repeat"><?php echo $this->__('Background repeat') ?></label>
							<div class="col-sm-8">
								<select class="input-text" name="background_repeat" id="background_repeat">
									<option value="0"><?php echo $this->__('No') ?></option>
									<option value="1"<?php if($this->_block->getBackgroundRepeat()): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="parallax"><?php echo $this->__('Parallax') ?></label>
							<div class="col-sm-8">
								<select class="input-text" name="parallax" id="parallax">
									<option value="0"><?php echo $this->__('No') ?></option>
									<option value="1"<?php if($this->_block->getParallax()): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="cover"><?php echo $this->__('Background Cover') ?></label>
							<div class="col-sm-8">
								<select class="input-text" name="background_cover" id="cover">
									<option value="0"><?php echo $this->__('No') ?></option>
									<option value="1"<?php if($this->_block->getBackgroundCover()): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="padding_top"><?php echo $this->__('Padding top') ?></label>
							<div class="col-sm-8">
								<input type="text" name="padding_top" id="padding_top" class="input-text validate-number" value="<?php echo $this->_block->getPaddingTop() ?>"/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="padding_bottom"><?php echo $this->__('Padding bottom') ?></label>
							<div class="col-sm-8">
								<input type="text" name="padding_bottom" id="padding_bottom" class="input-text validate-number" value="<?php echo $this->_block->getPaddingBottom() ?>"/>
							</div>
						</div>
					</div>
					
					<div class="tab-pane" id="product">
						<div class="form-group">
							<label class="col-sm-4 control-label" for="block_cols"><?php echo $this->__('Divide columns') ?></label>
							<div class="col-sm-8">
								<div class="vc-icon-option icon-prefix cols">
									<?php foreach($this->helper('mpanel')->getBlockCols() as $value=>$image): ?>
										<a href="#"<?php if($this->_block->getBlockCols()==$value): ?> class="active"<?php endif ?> onclick="setColValue('<?php echo $value ?>', this); return false"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>mpanel/cols/<?php echo $image ?>" alt="" style="max-width:100%"/></a>
									<?php endforeach ?>
								</div>
								<p><?php echo $this->__('Or input by yourself:') ?></p>
								<input type="text" name="block_cols" value="<?php echo $this->_block->getBlockCols() ?>" class="input-text" id="block_cols" onchange="addBlockClass()"/>
								<span class="note"><em class="fa fa-caret-up"></em><?php echo $this->__('Comma-separated.') ?></span>
							</div>
						</div>
						<?php 
							$html = '';
							if($this->_blockId && $this->_block->getBlockClass()!=''){
								$blockClass = $this->_block->getBlockClass();
								$blockClass = json_decode($blockClass, true);
								foreach($blockClass as $key=>$_class){
									$html .= '<div class="form-group"><label class="col-sm-4 control-label">'.$this->__('Custom class for Column %s', $key+1).'</label><div class="col-sm-8"><input type="text" name="block_class[]" class="input-text" value="'.$_class.'"/></div></div>';
								}
							}
						?>
						
						<div id="blocks-class"><?php echo $html ?></div>
					</div>
				</div>
			</div>
		
			<div class="row">
				<div class="form-group">
					<div class="col-md-12 builder-action">
						<div class="buttons">
							<input type="submit" value="Submit" class="btn btn-primary"/>
						</div>
					</div>
				</div>
			</div>
		</div>

	</form>
</div>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('block-form');
//]]>
	function setColValue(val, el){
		mgsjQuery('.vc-icon-option a').removeClass('active');
		mgsjQuery(el).addClass('active');
		mgsjQuery('#block_cols').val(val);
		addBlockClass();
	}
	
	function addBlockClass(){
		columns = mgsjQuery('#block_cols').val();
		if(columns==''){
			columns = '12';
		}
		var htmlInput = '';
		var divide = columns.split(",");
		
		<?php if($this->_blockId):?>
			if(columns=='<?php echo $this->_block->getBlockCols() ?>'){
				htmlInput = '<?php echo $html ?>';
			}
		<?php endif ?>
		
		if(htmlInput==''){
			for (var i=0; i < divide.length; i++) {
				htmlInput += '<div class="form-group"><label class="col-sm-4 control-label"><?php echo $this->__('Custom class for Column ') ?>'+ parseInt(i+1) +'</label><div class="col-sm-8"><input type="text" name="block_class[]" class="input-text" value=""/></div></div>';
			}
		}
		mgsjQuery('#blocks-class').html(htmlInput);
	}
</script>
	
<?php if(Mage::getSingleton('core/session')->getSaved()==1): ?>
	<?php Mage::getSingleton('core/session')->setSaved(false); ?>
	
	<script type="text/javascript">
		parent.loadHomepageContent();
		if (window.parent == window.top) {
			window.parent.mgsjQuery.magnificPopup.close();
		}
	</script>
<?php endif ?>