<?php
$category = Mage::getModel('catalog/category')->load($this->getRequest()->getParam('id'));
?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo $this->__('Edit Description') ?></h2>
        </div>
    </div>
    <form action="<?php echo $this->getUrl('mpanel/post/categoryDescription') ?>" method="POST" enctype="multipart/form-data">
        <div class="form-horizontal row margin-top15">
            <input type="hidden" name="id" value="<?php echo $category->getId(); ?>"/>
            <div class="form-group">
                <label for="description" class="col-sm-2 control-label"><?php echo $this->__('Description') ?></label>
                <div class="col-sm-10 image-input">                    
                    <textarea class="textarea input-text" cols="15" rows="15" name="description"><?php echo $category->getDescription(); ?></textarea>
                </div>
            </div>
            <div class="form-group builder-action">
                <div class="buttons">
                    <button class="btn btn-primary" type="submit"><span><span><?php echo $this->__('Update') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
</div>
<?php if ($this->getRequest()->getPost()): ?>
    <script type="text/javascript">
    <?php if (Mage::getSingleton('core/session')->getSaved() == 1): ?>
        <?php Mage::getSingleton('core/session')->setSaved(false); ?>
            window.parent.jQuery.magnificPopup.close();
            if (window.parent == window.top) {
                window.top.location.reload();
            }
    <?php endif ?>
    </script>
<?php endif; ?>