<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
	<div class="edit-static-form">
		<?php 
			$form = new Varien_Data_Form(
				array('id' => 'edit_form', 'action' => '', 'method' => 'post')
			);
			
			$form->setHtmlIdPrefix('block_');
			
			$fieldset = $form->addFieldset('base_fieldset', array('legend'=>'', 'class' => 'fieldset-wide'));
			
			$fieldset->addField('content', 'editor', array(
				'name'      => 'content',
				'label'     => '',
				'title'     => '',
				'style'     => 'height:22em',
				'config'    => $helper->getConfig()
			));
			
			$form->setUseContainer(true);
			//echo '<pre>'; print_r($helper->getConfig()); die();
			
			echo $form->toHtml();
		?>
	</div>
<?php endif ?>