<?php $helper = $this->helper('mpanel') ?>
<?php $blockId = $helper->getBlockIdByIndentifier('mpanel_contact_information'); ?>
<?php if($helper->acceptToUsePanel()): ?>
	<div class="edit-static-form">
		<div class="row">
			<div class="col-md-12 builder-title">
				<h2><?php echo $this->__('Edit Contact Information') ?></h2>
			</div>
		</div>
		<?php 
			$form = new Varien_Data_Form(
				array('id' => 'edit_form', 'action' => $this->getUrl('mpanel/post/static'), 'method' => 'post')
			);
			
			$form->setHtmlIdPrefix('block_');
			$fieldset = $form->addFieldset('base_fieldset', array('legend'=>'', 'class' => 'fieldset-wide'));
			$static = Mage::getModel('cms/block')->load($blockId);
			
			$fieldset->addField('block_id', 'hidden', array(
				'name'      => 'block_id',
			));
			
			$fieldset->addField('title', 'hidden', array(
				'name'      => 'title',
			));
			
			$fieldset->addField('identifier', 'hidden', array(
				'name'      => 'identifier',
			));
			
			$fieldset->addField('content', 'editor', array(
				'name'      => 'content',
				'label'     => '',
				'title'     => '',
				'class'		=> 'input-text',
				'style'     => 'height:22em',
				'config'    => $helper->getConfig(),
				'required'  => true,
			));

			$form->setUseContainer(true);

			$values = $static->getData();
			$form->setValues($values);


			echo $form->toHtml();
		?>
	</div>
	
	
	<script type="text/javascript">
		mgsjQuery("#block_base_fieldset").append( '<div class="builder-action"><div class="buttons"><button type="button" class="btn btn-primary" onclick="updateForm.submit(this)" id="submit-button"><span><span><?php echo $this->__('Submit') ?></span></span></button></div></div>' );
		
		var updateForm = new VarienForm('edit_form');
		
		updateForm.submit = function(button, url) {
		
			if (this.validator.validate()) {
				mgsjQuery('#submit-button span span').html('<?php echo $this->__('Saving...') ?>');
				mgsjQuery('#toggleblock_content').click();
				button.disabled = true;
				var form = this.form;
				var oldUrl = form.action;

				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					mgsjQuery.ajax({
						type: 'POST',
						url: form.action,
						dataType : 'json',
						data: mgsjQuery('#edit_form').serialize(),
						success: function(data, textStatus, xhr){
							if(data.result=='success'){
								button.disabled = false;
								mgsjQuery('#submit-button span span').html('<?php echo $this->__('Submit') ?>');
								window.parent.jQuery('#contact-information').html(data.content);
								if (window.parent == window.top) {
									window.parent.jQuery.magnificPopup.close();
								}
							}
						}
					});
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}

				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(updateForm);
		
	</script>
	
	
	<?php if(Mage::getSingleton('core/session')->getSaved()==1): ?>
		<?php Mage::getSingleton('core/session')->setSaved(false); ?>
		<script type="text/javascript">
			if (window.parent == window.top) {
				window.top.location.reload();
			}
		</script>
	<?php endif ?>
<?php endif ?>