<?php $settings = $this->helper('mpanel')->getThemeSettings() ?>
<div class="edit-static-form">
	<div class="row">
		<div class="col-md-12 builder-title">
			<h2><?php echo $this->__('Upload Logo') ?></h2>
		</div>
	</div>
	<form action="<?php echo $this->getUrl('mpanel/post/logo') ?>" method="POST" enctype="multipart/form-data" id="change-header-form">
		<div class="form-horizontal row margin-top15">
			<input type="hidden" name="header-logo" value="1"/>
			<div class="form-group">
				<label for="logo" class="col-sm-3 control-label"><?php echo $this->__('Upload logo') ?></label>
				<div class="col-sm-4 image-input">
					<input type="file" id="logo" name="groups[general][fields][logo][value]"/>
					
					<input type="hidden" value="<?php echo $settings['logo'] ?>" name="groups[general][fields][logo][value][value]" />
				</div>
			</div>
			
			<div class="form-group builder-action">
				<div class="buttons">
					<button class="btn btn-primary" type="submit"><span><span><?php echo $this->__('Update') ?></span></span></button>
				</div>
			</div>
		</div>
	</form>
</div>

<?php if($this->getRequest()->getPost()):?>

	<script type="text/javascript">
		<?php if(Mage::getSingleton('core/session')->getSaved()==1): ?>
		<?php Mage::getSingleton('core/session')->setSaved(false); ?>

			if (window.parent == window.top) {
				window.top.location.reload();
			}

		<?php endif ?>
	</script>

<?php endif ?>