<!DOCTYPE HTML>
<html lang="<?php echo $this->getLang(); ?>">
	<head>
		<?php echo $this->getChildHtml('head') ?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body <?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
		<?php $helper = $this->helper('mpanel') ?>
		<?php if($helper->isHomepage()): ?>
			<div class="messsges-block-home">
				<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
			</div>
		<?php endif ?>
		<?php echo $this->getChildHtml('after_body_start') ?>
		
		<?php  $helper = Mage::helper('mpanel'); $setting = $helper->getThemeSettings(); ?>
		<?php if($setting['layout']=='boxed'): ?>
			<div id="wrapper">
		<?php endif ?>
		
		<?php echo $this->getChildHtml('global_notices') ?>
		<header>
			<?php echo $this->getChildHtml('header') ?>
		</header>
		<section id="after-header">
			<div class="container">
				<?php echo $this->getChildHtml('slider') ?>
			</div>
		</section>
		<?php if($helper->isHomepage() && $helper->useHomepageBuilder()): ?>
			<section id="maincontent" <?php if(Mage::getStoreConfig('mgs_theme/general/header') == 'header2'): ?>class="left-header2"<?php endif;?>>
				<div class="container">
					<div class="row">
						<?php echo $this->getChildHtml('global_messages') ?>
					</div>
				</div>
				
				<div id="homepage-content-container">
					<?php echo $helper->getLayoutConfig() ?>
				</div>
			</section>
			
		<?php else: ?>
			<section id="maincontent" <?php if(Mage::getStoreConfig('mgs_theme/general/header') == 'header2'): ?>class="left-header2"<?php endif;?>>
				<?php echo $this->getChildHtml('breadcrumbs') ?> 
				<div class="container">

						
					<div class="row">
						<div class="col-main col-md-12">
							<?php echo $this->getChildHtml('global_messages') ?>
							<?php echo $this->getChildHtml('content') ?>
						</div>
					</div>


				</div>
			</section>
		<?php endif ?>
		<footer id="footer" <?php if(Mage::getStoreConfig('mgs_theme/general/header') == 'header2'): ?>class="left-header2"<?php endif;?>>
			<?php echo $this->getChildHtml('footer') ?>
		</footer>
		
		<?php if($setting['layout']=='boxed'): ?>
			</div>
		<?php endif ?>
		
		<?php echo $this->getChildHtml('before_body_end') ?>
		<?php echo $this->getAbsoluteFooter() ?>
		<?php echo $this->getChildHtml('theme_popup') ?>
	</body>
</html>