<?php
/* * ****************************************************
 * Package   : AjaxCart
 * Author    : http://www.arrowhitech.com
 * Copyright : (c) 2013 - ArrowHiTech.Com
 * ***************************************************** */
?>
<div class="loader" id="success-message-container">
    <p style="margin: 0;"><?php echo $this->__('Item(s) was added in your shopping cart.') ?></p>    
    <br><br>
    <button class="button btn-cart" id="finish_and_checkout" onclick="window.location.href = '<?php echo $this->getUrl('checkout/cart') ?>'" name="finish_and_checkout" type="button">
        <span>
            <span><?php echo $this->__('Go to cart page') ?></span>                    
        </span>
    </button>
    <br><br>
    <button class="button btn-cart" id="continue_shopping" onclick="closeMgs()" name="continue_shopping" type="button">
        <span>
            <span><?php echo $this->__('Continue shopping') ?></span>                                    
        </span>
    </button>
</div>
<script type="text/javascript">
    function closeMgs() {
        mgsjQuery.magnificPopup.close();
    }
</script>