<?php
/* * ****************************************************
 * Package   : ProductQuestions
 * Author    : http://www.arrowhitech.com
 * Copyright : (c) 2013 - ArrowHiTech.Com
 * ***************************************************** */
?>
<form id="search-form" method="get" action="<?php echo Mage::helper('productquestions')->faqsPageUrl() ?>" method="get">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('productquestions')->__('Search') ?></h2>
        <ul class="form-list">
            <li class="fields">
			<div class="row">
                <div class="field col-md-6 col-sm-8 col-xs-12">
                    <label for="query" class="required"><?php echo Mage::helper('productquestions')->__('Keyword') ?></label>
                    <div class="input-box">
                        <input name="query" id="query" title="<?php echo Mage::helper('productquestions')->__('Keyword') ?>" <?php if ($this->getRequest()->getParam('query')): ?>value="<?php echo $this->getRequest()->getParam('query'); ?>"<?php endif; ?> class="input-text required-entry" type="text" />
                    </div>
                </div>  
				<div class="buttons-set col-md-6 col-sm-4 col-xs-12">               
					<button type="submit" title="<?php echo Mage::helper('productquestions')->__('Search') ?>" class="btn btn-primary btn-md"><span><span><?php echo Mage::helper('productquestions')->__('Search') ?></span></span></button>        
				</div> 
			</div>
            </li>                                
        </ul>        
    </div>
</form>
<script type="text/javascript">
    var searchForm = new VarienForm('search-form');
</script>
