<?php $helper = $this->helper('mpanel') ?>
<div class="home-1column-full">
	<?php $block = $this->getBlocks() ?>
	<?php if(count($block)>0): ?>
		<?php foreach($block as $_block): ?>
			<section<?php echo $this->getBlockSetting($_block) ?>>
				<div class="<?php echo $this->getContainerSetting($_block) ?>">
					<?php 
						$cols = $this->getBlockCols($_block);
						$class = $_block->getBlockClass();
						if($class!=''){
							$class = json_decode($class, true);
						}
					?>
					<?php if(count($cols)>1): ?>
						<div class="row">
							<?php foreach($cols as $key=>$col): ?>
								<div class="col-md-<?php echo $col ?><?php if(is_array($class) && isset($class[$key])): ?> <?php echo $class[$key] ?><?php endif ?>">
									<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName($_block->getName().'-'.$key)->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
								</div>
							<?php endforeach ?>
						</div>
					<?php else: ?>
						
						<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName($_block->getName().'-0')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
					<?php endif ?>
				</div>
			</section>
		<?php endforeach ?>
	<?php endif ?>
</div>