<?php $portfolios = $this->getPortfolios() ?>
<div class="portfolio-container">
	<?php if($this->getTitle()): ?>
		<div class="title-content">
			<h2><?php echo $this->getTitle() ?></h2>
		</div>
	<?php endif ?>
	<?php if(count($portfolios)>0): ?>
		<?php 
			$helper = $this->helper('mpanel');
			$col = $this->getColumn();
			$col = $helper->convertColRowCustom($col);
		?>
		<div class="row">
		<?php if($this->getSlider()==1): ?>
			<div class="owl-carousel portfolio-carousel portfolio-grid" id="portfolio_carousel">
		<?php else: ?>
			<div class="portfolio-grid<?php if($col == 'custom-5' || $col == 'custom-7' || $col == 'custom-8'): ?> products-grid-<?php echo $col; ?><?php endif; ?>">
		<?php endif ?>
			<?php foreach($portfolios as $portfolio): ?>
				<?php if($this->getSlider()==1): ?>
					<div class="item">
				<?php else: ?>
					<div class="item <?php if($col !=''): ?>col-md-<?php echo $col; ?> col-sm-6 col-xs-12<?php endif; ?>">
				<?php endif ?>
					<div class="portfolio-top-content">
						<a href="<?php echo $this->getUrl('portfolio/view/index', array('id'=>$portfolio->getId())) ?>"><img src="<?php echo $this->helper('portfolio')->getThumbnail($portfolio)?>" alt="" class="img-responsive"/></a>
						<div class="hover-info">
							<div class="text-info text-center">
								<p class="icon-portfolio"><a href="<?php echo $this->getUrl('portfolio/view/index', array('id'=>$portfolio->getId())) ?>"><span class="fa fa-search"></span></a></p>
								<p class="project"><span><?php echo $portfolio->getServices() ?></span></p>
								<p class="categories text-uppercase"><span><?php echo $this->helper('portfolio')->getCategoriesText($portfolio)?></span></p>
							</div>
						</div>
					</div>
					<div class="portfolio-bottom-content text-center">
						<p class="portfolio-name"><a href="<?php echo $this->getUrl('portfolio/view/index', array('id'=>$portfolio->getId())) ?>"><?php echo $portfolio->getName() ?></a></p>
						<p class="category-link text-uppercase color-theme"><?php echo $this->helper('portfolio')->getCategoriesLink($portfolio)?></p>
					</div>
				</div>
			<?php endforeach ?>
			
			</div>
		</div>
		<?php if($this->getSlider()==1): ?>
			<script type="text/javascript">
				initSlider('portfolio_carousel', <?php echo $this->getColumn() ?>, <?php echo $this->getAutoPlay()?>, <?php echo $this->getStopHover()?>, <?php echo $this->getNavigation()?>, <?php echo $this->getPagination()?>);
			</script>
		<?php endif ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There are no portfolios matching the selection.') ?></p>
	<?php endif ?>
</div>