<?php if (Mage::getStoreConfig(AW_Blog_Helper_Config::XML_TAGCLOUD_SIZE) && $this->getCollection()->count()): ?>
    <div class="block block-tag menu-tags">
		<div class="title-block">
			<h4><?php echo Mage::helper('blog')->__('Tags'); ?></h4>
		</div>
        <div class="block-content">
			<div class="tagcloud">
				<?php foreach ($this->getCollection() as $tag): ?>
					<a class="tag-count-<?php echo $this->getTagWeight($tag) ?>" href="<?php echo $this->getTagHref($tag) ?>"><?php echo $tag->getTag() ?></a>
				<?php endforeach; ?>
			</div>
		</div>
    </div>
<?php endif; ?>