<?php
/**
 * @name         :  MGS One Step Checkout
 * @version      :  1.4
 * @since        :  Magento ver 1.4, 1.5, 1.6, 1.7
 * @author       :  MGS - http://www.mage-shop.com
 * @copyright    :  Copyright (C) 2011 Powered by MGS
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  Sept 06 2012
 * 
 * */ ?>
<button type="button" title="<?php echo Mage::helper('oscheckout')->__('Place Order') ?>" class="button btn-checkout" onclick="review.save();"><span><span><?php echo Mage::helper('oscheckout')->__('Place Order') ?></span></span></button>
