<?php

$productCount = 6; 
$storeId = Mage::app()->getStore()->getId();


$storeId = (int) Mage::app()->getStore()->getId();
 
        
        $date = new Zend_Date();
        $toDate = $date->setDay(1)->getDate()->get('Y-MM-dd');
        $fromDate = $date->subMonth(1)->getDate()->get('Y-MM-dd');
 
        $collection = Mage::getResourceModel('catalog/product_collection')
            ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
            ->addStoreFilter()
            ->addPriceData()
            ->addTaxPercents()
            ->addUrlRewrite()
            ->setPageSize($productCount);
 
        $collection->getSelect()
            ->joinLeft(
                array('aggregation' => $collection->getResource()->getTable('sales/bestsellers_aggregated_monthly')),
                "e.entity_id = aggregation.product_id AND aggregation.store_id={$storeId}",
                array('SUM(aggregation.qty_ordered) AS sold_quantity')
            )
            ->group('e.entity_id')
            ->order(array('sold_quantity DESC', 'e.created_at'));
 
        Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
        Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
 


?>


<?php if ($this->getTitle() != ''): ?>
    <div class="block-view">
        <div class="title-content">
            <h3><?php echo $this->getTitle() ?></h3>
        </div>
    </div>
<?php endif ?>
<?php $_products = $collection; ?>
<?php if ($_products): ?>
    <?php $helper = $this->helper('mpanel') ?>
    <?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
    <?php
    if ($this->getCountPerRow()) {
        $col = $this->getCountPerRow();
    } else {
        $col = 3;
    }
    $perrow = $col;
   
    $col = $helper->convertColRowCustom($col);
    ?>
    <?php $catId = ''; ?>
    <?php if ($this->getCategoryId() != ''): ?>
        <?php $catId = $this->getCategoryId() ?>
    <?php endif ?>

    
        
        <?php $_collectionSize = count($_products) ?>
        <?php $_columnCount = 1; ?>
        <?php if ($this->getNumberRow() != ''): ?>
            <?php $_columnCount = $this->getNumberRow() * $this->getCountPerRow(); ?>
        <?php endif ?>
        <div class="row">
            <div class="products-grid <?php if ($this->getNumberRow() > 1): ?>slider-multiple-row<?php endif ?>">
                <div class="<?php if ($this->getNumberRow() != 1): ?><?php if ($col == 'custom-5' || $col == 'custom-7' || $col == 'custom-8'): ?> col-md-<?php echo $col; ?><?php endif; ?><?php endif; ?> products-carousel product-category-tab row-<?php echo $perrow ?>" id="new_products<?php echo $catId ?>">
                    <?php $i = 0; $j = 0; foreach ($_products as $_product): $j++; ?>
                        <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
                        <?php if ($this->getNumberRow() > 1): ?>
                            <?php if ($i++ % $_columnCount == 0): ?>
                                <div class="item">
                            <?php endif ?>
                        <?php endif ?>
            <?php if ($this->getNumberRow() > 1): ?>
            <?php $class = $helper->getItemClass($perrow, $j) ?>
              <div class="<?php if ($col != ''): ?>col-md-<?php echo $col; ?> col-sm-4 col-xs-12  col-xs-half<?php endif; ?><?php if($j %  $perrow == 1):?> first-row-item <?php endif ?><?php echo $class ?>">
            <?php else: ?>
              <div class="item">
            <?php endif ?>
                <div class="product-content">
                  <div class="product-top">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                      <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
                      <?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
                        alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
                      <?php endif ?>
                    </a>
                    <?php echo $helper->getProductLabel($_product) ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <ul class="icon-links">
                    <?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
                      <li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-eye"></em></button></li>
                    <?php endif ?>
                    <?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
                      <li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
                    <?php endif; ?>
                    <?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
                    <?php if($_compareUrl && $helper->isShowCompare()): ?>
                      <li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
                    <?php endif; ?>
                    </ul>
                  </div>
                  <div class="product-desc">
                    <h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
                    <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                    <div class="controls">
                    <?php if($helper->isShowAddtoCart()): ?>
                      <div class="add-to-cart">
                        <?php if ($_product->isSaleable()): ?>
                          <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-xs btn-primary" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
                        <?php else: ?>
                          <p class="h6"><?php echo $this->__('Sold') ?></p>
                        <?php endif; ?>
                      </div>
                    <?php endif ?>
                    </div>
                  </div>
                </div>                                
              </div>
            <?php if ($this->getNumberRow() > 1): ?>
              <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </div>
              <?php endif ?>
                        <?php endif ?>
          <?php endforeach ?>
                </div>
      </div>
    </div>
            
           
           

        
<?php else: ?>
    <div class="alert alert-danger no-product-display">
        <p><?php echo $this->__('There are no products matching the selection.') ?></p>
    </div>
<?php endif; ?>
