<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('mgs/mpanel/template/1column/homepage1.phtml')->toHtml() ?>

<?php $cmsPageUrlKey = Mage::getSingleton('cms/page')->getIdentifier(); ?>
<?php $pageId = Mage::getBlockSingleton('cms/page')->getPage()->getId(); ?>
<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
	
	
	<?php 
		$form = new Varien_Data_Form(
            array('id' => 'edit_form', 'action' => '', 'method' => 'post')
        );
		
		$form->setHtmlIdPrefix('block_');
		
		$fieldset = $form->addFieldset('base_fieldset', array('legend'=>'', 'class' => 'fieldset-wide'));
		
		$fieldset->addField('content', 'editor', array(
            'name'      => 'content',
            'label'     => '',
            'title'     => '',
            'style'     => 'height:36em',
            'config'    => $helper->getConfig()
        ));
		
		$form->setUseContainer(true);
		
		//echo $form->toHtml();
	?>
	
	<?php //echo $this->getFormHtml();?>
<?php endif ?>

<!--button style="" onclick="MediabrowserUtility.openDialog('http://g3.arrowhitech.net/magento_panel/index.php/mpanel/edit/popup/type//id/', null, null, 'Test')" class="scalable plugin" type="button" title="Test"><span><span><span>Test</span></span></span></button-->