<?php $helper = $this->helper('mpanel') ?>
<?php if ($helper->acceptToUsePanel()): ?>
    <div class="edit-static-form">
        <div class="row">
            <div class="col-md-12 builder-title">
                <h2><?php echo $this->__('Static Block For Custom Tab') ?></h2>
            </div>
        </div>
        <?php
        $form = new Varien_Data_Form(
                array('id' => 'edit_form', 'action' => $this->getUrl('mpanel/post/createStaticBlock'), 'method' => 'post')
        );

        $form->setHtmlIdPrefix('block_');

        $fieldset = $form->addFieldset('base_fieldset', array('legend' => '', 'class' => 'fieldset-wide-custom'));        
        
        $fieldset->addField('title', 'text', array(
            'name' => 'title',
            'label' => $this->__('Block Title'),
            'title' => $this->__('Block Title'),
            'required' => true,
        ));

        $fieldset->addField('identifier', 'text', array(
            'name' => 'identifier',
            'label' => $this->__('Identifier'),
            'title' => $this->__('Identifier'),
            'required' => true,
            'class' => 'validate-xml-identifier',
        ));

        $fieldset->addField('store_id', 'hidden', array(
            'name' => 'stores[]',
            'value' => Mage::app()->getStore()->getStoreId()
        ));

        $fieldset->addField('is_active', 'hidden', array(
            'name' => 'is_active',
            'value' => 1
        ));

        $fieldset->addField('content', 'editor', array(
            'name' => 'content',
            'label' => $this->__('Content'),
            'title' => $this->__('Content'),
            'style' => 'height:22em',
            'required' => true,
            'config' => $helper->getConfig()
        ));

        $form->setUseContainer(true);

        echo $form->toHtml();
        ?>
    </div>



    <script type="text/javascript">
        mgsjQuery("#block_base_fieldset").append('<div class="builder-action"><div class="buttons"><button type="button" class="btn btn-primary" onclick="updateForm.submit(this)" id="submit-button"><span><span><?php echo $this->__('Submit') ?></span></span></button></div></div>');
        var updateForm = new VarienForm('edit_form');
        updateForm.submit = function (button, url) {
            if (this.validator.validate()) {
                mgsjQuery('#submit-button span span').html('<?php echo $this->__('Saving...') ?>');
                mgsjQuery('#toggleblock_content').click();
                button.disabled = true;
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                    form.action = url;
                }
                var e = null;
                try {
                    mgsjQuery.ajax({
                        type: 'POST',
                        url: form.action,
                        dataType: 'json',
                        data: mgsjQuery('#edit_form').serialize(),
                        success: function (data, textStatus, xhr) {
                            if (data.result == 'success') {
                                button.disabled = false;
                                mgsjQuery('#submit-button span span').html('<?php echo $this->__('Submit') ?>');
//                                if (window.parent == window.top) {
//                                    window.parent.mgsjQuery.magnificPopup.close();
//                                    window.top.location.reload();
//                                }
                                window.location.href = '<?php echo $this->getUrl('mpanel/index/createProductTab'); ?>' + 'type/static/' + 'value/' + data.value + '/';
                            }
                        }
                    });
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(updateForm);

    </script>
<?php endif; ?>