<?php if(Mage::getStoreConfig('social/flickr/active') == 1 && Mage::getStoreConfig('social/flickr/client_id') && Mage::getStoreConfig('social/flickr/user_id')): ?>
<?php $client_id = Mage::getStoreConfig('social/flickr/client_id'); ?>
<?php $user_id = Mage::getStoreConfig('social/flickr/user_id'); ?>
<?php $this->helper('mpanel/social')->getFlickrData($client_id, $user_id); ?>
<?php else: ?>
<div class="alert alert-warning">
	<?php echo $this->__('Please update your flick photo settings first.') ?>
</div>
<?php endif; ?>