<?php 
	$form = new Varien_Data_Form();

	$fieldset = $form->addFieldset('base_fieldset', array(
		'legend'    => $this->helper('widget')->__('Widget')
	));

	$select = $fieldset->addField('select_widget_type', 'select', array(
		'label'                 => $this->helper('widget')->__('Widget Type'),
		'title'                 => $this->helper('widget')->__('Widget Type'),
		'name'                  => 'widget_type',
		'required'              => true,
		'options'               => $this->_getWidgetSelectOptions(),
		'after_element_html'    => $this->_getWidgetSelectAfterHtml(),
	));

	$form->setUseContainer(true);
	$form->setId('widget_options_form');
	$form->setMethod('post');
	$form->setAction($this->getUrl('*/*/buildWidget'));
	echo $form->toHtml();
?>

<script type="text/javascript">
	wWidget = new WysiwygWidget.Widget("widget_options_form", "select_widget_type", "widget_options", "<?php echo $this->getUrl('mpanel/adminhtml_widget/loadOptions') ?>", "<?php echo $this->getRequest()->getParam('widget_target_id') ?>");
</script>