<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
	$_helper = $this->helper('catalog/output');
?>
<?php if($this->getTitle()!=''): ?>
	<div class="carousel_wrapper">
		<div class="title">
			<h2><?php echo $this->getTitle() ?></h2>
		</div>
	</div>
<?php endif ?>

<?php if(count($categories)>0): ?>
	<div class="category-products-masonry">
		<?php foreach($categories as $_category): ?>
			<div class="category-product-item">
				<?php $products = $this->getProductByCategory($_category) ?>
				<?php if(count($products)>0): ?>
				
					<div class="masonry-grid" id="category-product-<?php echo $_category->getId() ?>">
						<?php foreach($products as $_product): ?>
							<?php //$_product = Mage::getModel('catalog/product')->load($_product) ?>
							<div class="item col-md-<?php echo $col; ?> col-sm-6 col-xs-12">
								<div class="wrapper-item">
									<div class="product-info-box product-hover">
										<div class="image-container">
											<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
												<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
												<span class="hover-display">&nbsp;</span>
											</a>
											<div class="actions">
												<div class="buttons">
													<?php if ($_product->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-primary btn-cart cart-product-grid" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__(' Add to Cart') ?></button>
										<?php endif; ?>
													<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
														<button class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><?php echo $this->__('Quick View') ?></button>
													<?php endif ?>
													
													<ul class="add-to-links tooltip-links">
														<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
															<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist btn" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart"></i></a></li>
														<?php endif; ?>
														<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
															<li><a href="<?php echo $_compareUrl ?>" class="link-compare btn" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></a></li>
														<?php endif; ?>
													</ul>
												</div>
											</div>
											<?php //echo $panelHelper->getProductLabel($_product) ?>
										</div>
										<div class="title-grid">
											<div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></div>
											
											<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
											
										</div>
										
										<div class="product-short-description">
											<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										</div>
									</div>
								</div>
							</div>
						<?php endforeach ?>
					</div>
				<?php endif ?>

			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>