<?php $_product = $this->getProduct() ?>
<div class="special-product">
    <?php if ($this->getTitle()): ?>
        <div class="block-title">
            <h2><?php echo $this->getTitle() ?></h2>
        </div>
    <?php endif ?>

    <?php if ($_product->getId()): ?>
        <?php $helper = $this->helper('mpanel') ?>
        <?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
        <div class="product-content">
            <div class="product-top">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
                </a>
                <?php echo $helper->getProductLabel($_product) ?>

                <?php if ($this->getShowRating()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
            </div>
			
            <?php if ($this->getShowName() || $this->getShowPrice() || $this->getShowAddcart() || $this->getShowWishlist() || $this->getShowCompare() || $this->getShowQuickview()): ?>
				<div class="product-desc">
					<?php if ($this->getShowName()): ?>
						<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a></h4>
					<?php endif ?>
					<?php if ($this->getShowPrice()): ?>
						<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
					<?php endif ?>
					<?php if ($this->getShowAddcart() || $this->getShowWishlist() || $this->getShowCompare() || $this->getShowQuickview()): ?>
						<div class="controls">
							<?php if ($this->getShowAddcart()): ?>
								<div class="add-to-cart">
									<?php if ($_product->isSaleable() && $this->getShowAddcart()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-xs btn-primary " onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add To Cart'); ?></button>
									<?php endif; ?>
								</div>
							<?php endif ?>
							<?php if ($this->getShowWishlist() || $this->getShowCompare() || $this->getShowQuickview()): ?>
								<ul class="icon-links">
									<?php if ($this->helper('wishlist')->isAllow() && $this->getShowWishlist()) : ?>
										<li><button type="button" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" class="link-wishlist btn" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart-o"></i></button></li>
									<?php endif; ?>
									
									<?php if(($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)) && $this->getShowCompare()): ?>
										<li><button type="button" onclick="setLocation('<?php echo $_compareUrl ?>')" class="link-compare btn" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></button></li>
									<?php endif; ?>
									
									<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active') && $this->getShowQuickview()): ?>
										<li><button type="button" class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></button></li>
									<?php endif ?>
								</ul>
							<?php endif ?>
						</div>
					<?php endif ?>
				</div>
			<?php endif ?>
        </div>
    <?php endif ?>
</div>
