<?php
$helper = $this->helper('mpanel');
$params = $this->getRequest()->getParams();
$pageId = $params['page_id'];
$productId = $params['product_id'];
$place = $params['place'];
?>
<?php if ($helper->acceptToUsePanel()): ?>    
    <div class="edit-static-form">
        <div class="row">
            <div class="col-md-12 builder-title">
                <h2><?php echo $this->__('Select Block'); ?></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="bs-glyphicons">
                    <ul class="bs-glyphicons-list" id="list-item">
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addStaticBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'static_block', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-text-width"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Static Block') ?></span>
                        </li>                                                
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCategoryNavigationBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'category_navigation', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-list-alt"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Category Navigation') ?></span>
                        </li>                          
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'sub_categories', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-list"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Sub Categories') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'cart_sidebar', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-shopping-cart"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Cart Sidebar') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'compare_sidebar', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-retweet"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Compare Sidebar') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'reorder_sidebar', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-align-justify"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Reorder Sidebar') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addPollBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'poll', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-align-left"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Poll') ?></span>
                        </li>
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'product_related', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-th"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Product Related') ?></span>
                        </li>
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'product_viewed', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-eye-open"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Product Viewed') ?></span>
                        </li>                         
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'wishlist_sidebar', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-heart"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Wishlist Sidebar') ?></span>
                        </li>                         
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'tags_popular', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-tags"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Tags Popular') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addCoreBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'newsletter', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-envelope"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Newsletter') ?></span>
                        </li>
						<?php if($this->helper('core')->isModuleEnabled('MGS_Promobanners')): ?>
							<li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addPromoBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'promo_banner', 'place' => $place)) ?>')">
								<span class="glyphicon glyphicon-gift"></span>
								<span class="glyphicon-class"><?php echo $this->__('Promo Banner') ?></span>
							</li>
						<?php endif ?>
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addMenuBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'menu', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-list"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Menu') ?></span>
                        </li>                         
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addProductBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'featured_products', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-th"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Featured Products') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addProductBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'bestseller_products', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-th"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Bestseller Products') ?></span>
                        </li>                         
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addProductBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'new_products', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-th"></span>
                            <span class="glyphicon-class"><?php echo $this->__('New Products') ?></span>
                        </li>                        
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addProductBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'top_rate_products', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-th"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Top Rate Products') ?></span>
                        </li>                         
                        <li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addProductBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'sale_products', 'place' => $place)) ?>')">
                            <span class="glyphicon glyphicon-th"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Sale Products') ?></span>
                        </li>
						<?php if($this->helper('mpanel/social')->checkBlockAccept('facebook')): ?>
							<li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addFacebookLikeBoxBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'facebook_like_box', 'place' => $place)) ?>')">
								<span class="glyphicon glyphicon-share"></span>
								<span class="glyphicon-class"><?php echo $this->__('Facebook Like Box') ?></span>
							</li>
						<?php endif ?>
						<?php if($this->helper('mpanel/social')->checkBlockAccept('twitter')): ?>
							<li onclick="setLocation('<?php echo $this->getUrl('mpanel/product/addTwitterFeedBlock', array('page_type' => 'product', 'page_id' => $pageId, 'product_id' => $productId, 'type' => 'twitter_feed', 'place' => $place)) ?>')">
								<span class="glyphicon glyphicon-share"></span>
								<span class="glyphicon-class"><?php echo $this->__('Twitter Feed') ?></span>
							</li>
						<?php endif ?>
                    </ul>
                </div>                
            </div>
        </div>
    </div>
<?php endif; ?>

