<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$model = $this->getBrand();
$helper = Mage::helper('brand');
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="brand-detail">
<?php if ($model->getImage() != ''): ?>
    <p class="category-image">
        <img class="img-responsive" title="<?php echo $model->getTitle(); ?>" alt="<?php echo $model->getTitle(); ?>"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $model->getImage(); ?>">
    </p>
<?php endif; ?>
<?php
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
?>
<?php if ($model->getDescription() != ''): ?>
    <div class="category-description std">
        <p><?php echo $model->getDescription(); ?></p>
    </div>
<?php endif; ?>

<?php if (!$_productCollection->count()): ?>
	<div class="alert alert-danger">
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	</div>
<?php else: ?>
    <div class="category-products">
		<div class="show-top">
			<?php echo $this->getToolbarHtml() ?>
		</div>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list category-products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                        <div class="row">
							<div class="col-md-3 col-sm-6 col-xs-12 col-sm-half">
								<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							</div>
							<div class="product-content col-md-9 col-sm-6 col-xs-12 col-sm-half">
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
								<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h6>
								<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short','');?>
								<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="desc std"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></div>
								<div class="controls">
									<ul class="icon-links">
										<?php if($panelHelper->isShowAddtoCart()): ?>
											<?php if ($_product->isSaleable()): ?>
												<li class="add-cart-item">
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-lg" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart'); ?></button>
												</li>
											<?php endif; ?>
										<?php endif; ?>
										<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
											<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" 
											onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-eye"></em></button></li>
										<?php endif ?>
										<?php if ($this->helper('wishlist')->isAllow() && $panelHelper->isShowWishList()) : ?>
											<li class="wl-item"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
										<?php endif; ?>
										<?php $_compareUrl = $this->getAddToCompareUrl($_product); ?>
										<?php if ($_compareUrl && $panelHelper->isShowCompare()): ?>
											<li><button class="btn-compare" type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
						</div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
				<div class="products-grid row">
					<?php $i = 0; foreach ($_productCollection as $_product): $i++ ; ?>
						<div class="item col-md-4 col-sm-6 col-xs-12 <?php if ($i % 3 == 1): ?>first-row-item <?php endif; ?><?php if ($i % 2 == 1): ?>row-2sm-first<?php endif; ?>">
						<div class="product-content">
							<div class="product-top">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
									<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
									<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
										<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
										alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
									<?php endif ?>
								</a>
								<?php echo $panelHelper->getProductLabel($_product) ?>
								<div class="controls">
									<ul class="icon-links">
										<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
											<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" 
											onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-eye"></em></button></li>
										<?php endif ?>
										<?php if ($this->helper('wishlist')->isAllow() && $panelHelper->isShowWishList()) : ?>
											<li class="wl-item"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
										<?php endif; ?>
										<?php $_compareUrl = $this->getAddToCompareUrl($_product); ?>
										<?php if ($_compareUrl && $panelHelper->isShowCompare()): ?>
											<li><button class="btn-compare" type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
								<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short','');?>
							</div>
							<div class="product-desc">
								<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
								<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
								<div class="controls">
									<?php if($panelHelper->isShowAddtoCart()): ?>
										<?php if ($_product->isSaleable()): ?>
											<div class="add-to-cart">
												<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><em class="fa fa-shopping-cart"></em></button>
											</div>
										<?php else: ?>
											<div class="add-to-cart">
												<span class="h6"><?php echo $this->__('SOLD'); ?></span>
											</div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
							</div>
						</div>
						</div>
					<?php endforeach ?>
                </div>
            <script
            type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>

        <div class="show-bottom  <?php if ($this->getMode() != 'grid'): ?>list-mode<?php endif ?>">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
</div>