<?php
if ($this->getTitle() != '') {
    $title = $this->getTitle();
} else {
    $title = 'Newsletter';
}
?>
<?php $megaMenu = $this->getMegamenuItems(); ?>
<?php if (count($megaMenu) > 0): ?>
    <ul id="vertical-menu-<?php echo $this->getMenuId() ?>" class="vertical-menu nav nav-pills nav-main">
        <?php if (count($megaMenu) > 0): ?>
            <?php
            $i = 0;
            foreach ($megaMenu as $item): $i++
                ?>
                <li class="<?php echo $this->getClass($item) ?>">
                    <?php echo $this->getMenuHtml($item) ?>
                </li>
            <?php endforeach ?>
        <?php endif ?>
    </ul>
<?php else: ?>
    <?php if (Mage::helper('mpanel')->acceptToUsePanel()): ?>
        <div class="title">
            <h3><?php echo $this->__($title); ?></h3>
        </div>
        <p><?php echo $this->__('Menu does not exists.'); ?></p>
    <?php endif; ?>
<?php endif ?>