<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
$_productStoreConfig = Mage::getStoreConfig('brand/product');
$_showBrand = $_productStoreConfig['show_brand'];
?>
<?php if ($_showBrand): ?>
    <?php
    $helper = Mage::helper('brand');
    $_product = Mage::registry('product');
    $_brand = $this->getBrand($_product->getId());
    $urlKey = $this->getUrlKey();
    $_showBrandImage = ($this->getData('show_brand_image') == "0") ? $this->getData('show_brand_image') : 1;
    $_showBrandTitle = ($this->getData('show_brand_title') == "0") ? $this->getData('show_brand_title') : 1;
    $_imageLinkToBrandPage = ($this->getData('image_link_to_brand_page') == "0") ? $this->getData('image_link_to_brand_page') : 1;
    $_titleLinkToBrandPage = ($this->getData('title_link_to_brand_page') == "0") ? $this->getData('title_link_to_brand_page') : 1;
    if ($helper->iconWidth() != '') {
        $iconWidth = $helper->iconWidth();
    } else {
        $iconWidth = 135;
    }
    if ($helper->iconHeight() != '') {
        $iconHeight = $helper->iconHeight();
    } else {
        $iconHeight = 135;
    }
    ?>

    <?php if ($_brand->getId()): ?>
        <div class="product-brand">
            <div class="product-brand-inner">
                <?php if ($_showBrandImage): ?>
                    <div class="brand-image">
                        <?php if ($_imageLinkToBrandPage): ?>
                            <a title="<?php echo $_brand->getTitle(); ?>"
                               href="<?php echo $this->getUrl() . $urlKey . '/' . $_brand->getUrlKey(); ?>">
					   <?php endif; ?>
					   <?php if ($_brand->getIcon() != ''): ?>
						<img class="brand-img" height="80" alt="<?php echo $_brand->getTitle(); ?>"
							 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $_brand->getIcon(); ?>">
						 <?php else: ?>
						<img class="brand-img" height="<?php echo $iconHeight; ?>" alt="<?php echo $_brand->getTitle(); ?>"
							 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/mgs/brand/no_image.jpg'; ?>">
						 <?php endif; ?>
						 <?php if ($_imageLinkToBrandPage): ?>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?> <!-- Check show brand -->