<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$model = $this->getBrand();
$helper = Mage::helper('brand');
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="brand-detail">
<?php if ($model->getImage() != ''): ?>
    <p class="category-image">
        <img class="img-responsive" title="<?php echo $model->getTitle(); ?>" alt="<?php echo $model->getTitle(); ?>"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $model->getImage(); ?>">
    </p>
<?php endif; ?>
<?php
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
?>
<?php if ($model->getDescription() != ''): ?>
    <div class="category-description std">
        <p><?php echo $model->getDescription(); ?></p>
    </div>
<?php endif; ?>

<?php if (!$_productCollection->count()): ?>
	<div class="alert alert-danger">
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	</div>
<?php else: ?>
    <div class="category-products">
		<div class="show-top">
			<?php echo $this->getToolbarHtml() ?>
		</div>

		<?php $_collectionSize = $_productCollection->count() ?>
		<?php $_columnCount = $this->getColumnCount(); ?>
			<div class="products-grid row">
				<?php $i = 0; foreach ($_productCollection as $_product): $i++ ; ?>
					<div class="item <?php if ($i % 2 == 1): ?>row-2sm-first<?php endif; ?>">
					<div class="product-content">
						<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
							</a>
							<?php echo $panelHelper->getProductLabel($_product) ?>
						</div>
						<div class="product-desc">
							<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
							<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
							<div class="controls">
								<?php if($panelHelper->isShowAddtoCart()): ?>
									<?php if ($_product->isSaleable()): ?>
										<div class="add-to-cart">
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><em class="fa fa-shopping-cart"></em></button>
										</div>
									<?php else: ?>
										<div class="add-to-cart">
											<span class="h6"><?php echo $this->__('SOLD'); ?></span>
										</div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						</div>
					</div>
					</div>
				<?php endforeach ?>
			</div>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>

        <div class="show-bottom  <?php if ($this->getMode() != 'grid'): ?>list-mode<?php endif ?>">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
</div>