<?php
/* * ****************************************************
 * Package   : ProductQuestions
 * Author    : http://www.arrowhitech.com
 * Copyright : (c) 2013 - ArrowHiTech.Com
 * ***************************************************** */
?>
<div class="faq"> 
    <div class="search">
        <?php echo $this->getChildHtml('productquestions.faq.search') ?>
    </div>
    <div class="content">
        <?php echo $this->getChildHtml('productquestions.faq.topic') ?>
    </div>
</div>