<?php
/* * ****************************************************
 * Package   : ProductQuestions
 * Author    : http://www.arrowhitech.com
 * Copyright : (c) 2013 - ArrowHiTech.Com
 * ***************************************************** */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $questions = $this->getQuestions(); ?>
<div class="boxed-content padding20">
	<div class="title-block">
		<h4><?php echo $this->__('My Questions') ?></h4>
	</div>
	<?php if (count($questions)): ?>
		<div class="table-responsive">
			<table class="data-table table-hover" id="my-questions-table">
				<col width="200">
				<col>
				<col width="1">
				<col width="1">
				<thead>
					<tr>
						<th><span class="nobr"><?php echo $this->__('Product') ?></span></th>
						<th><span class="nobr"><?php echo $this->__('Question') ?></span></th>
						<th><span class="nobr"><?php echo $this->__('Status') ?></span></th>
						<th><span class="nobr"><?php echo $this->__('Is Answered?') ?></span></th>                
					</tr>
				</thead>
				<tbody>            
					<?php foreach ($questions as $question): ?>
						<tr>
							<?php
							$product = Mage::getModel('catalog/product')->load($question->getProductId());
							$productUrl = $product->getProductUrl();
							?>
							<td><a title="<?php echo $question->getProductName(); ?>" href="<?php echo $productUrl; ?>"><?php echo $question->getProductName(); ?></a></td>
							<td><?php echo $question->getContent(); ?></td>
							<?php
							if ($question->getStatus() == 1) {
								$status = 'Pending';
							} elseif ($question->getStatus() == 2) {
								$status = 'Approved';
							} else {
								$status = 'Declined';
							}
							?>
							<td><?php echo $status; ?></td>   
							<?php $answersByQuestionId = $this->getAnswersByQuestionId($question->getId()); ?>
							<?php if (count($answersByQuestionId)): ?>
								<td><span class="nobr"><?php echo $this->__('Yes ' . '- ' . count($answersByQuestionId) . ' answer(s)') ?></span></td> 
							<?php else: ?>
								<td><span class="nobr"><?php echo $this->__('Not yet.') ?></span></td> 
							<?php endif; ?>                               
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<script type="text/javascript">decorateTable('my-questions-table');</script>
		<div class="toolbar text-right toolbar-history-order">
			<?php echo $this->getPagerHtml(); ?>
		</div>
	<?php else: ?>
		<p><?php echo $this->__('You have placed no questions.'); ?></p>
	<?php endif ?>
</div>
<div class="boxed-content padding20 margin-top30">
	<?php $answers = $this->getAnswers(); ?>
	<div class="title-block">
		<h4><?php echo $this->__('My Answers') ?></h4>
	</div>
	<?php echo $this->getPagerAnswerHtml(); ?>
	<?php if (count($answers)): ?>
		<div class="table-responsive"></div>
			<table class="data-table table-hover" id="my-answers-table">
				<col width="200">
				<col>
				<col width="1">
				<col width="1">
				<thead>
					<tr>
						<th><span class="nobr"><?php echo $this->__('Product') ?></span></th>
						<th><span class="nobr"><?php echo $this->__('Question') ?></span></th>
						<th><span class="nobr"><?php echo $this->__('Answer') ?></span></th>
						<th><span class="nobr"><?php echo $this->__('Status') ?></span></th>                
					</tr>
				</thead>
				<tbody>            
					<?php foreach ($answers as $answer): ?>
						<tr>
							<?php
							$question = Mage::getModel('productquestions/question')->load($answer->getQuestionId());
							$product = Mage::getModel('catalog/product')->load($question->getProductId());
							$productUrl = $product->getProductUrl();
							?>
							<td><a title="<?php echo $question->getProductName(); ?>" href="<?php echo $productUrl; ?>"><?php echo $question->getProductName(); ?></a></td>
							<td><?php echo $question->getContent(); ?></td>
							<td><?php echo $answer->getAContent(); ?></td>
							<?php
							if ($answer->getAStatus() == 1) {
								$status = 'Pending';
							} elseif ($answer->getAStatus() == 2) {
								$status = 'Approved';
							} else {
								$status = 'Declined';
							}
							?>
							<td><?php echo $status; ?></td>                                                     
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<script type="text/javascript">decorateTable('my-answers-table');</script>
		<div class="toolbar text-right toolbar-history-order">
			<?php echo $this->getPagerAnswerHtml(); ?>
		</div>
	<?php else: ?>
		<p><?php echo $this->__('You have placed no answers.'); ?></p>
	<?php endif ?>
</div>