<?php $testimonials = $this->getTestimonialsPager(); 
	$pager = $this->getCount() / $this->getPerPage();
	if($this->getCount() % $this->getPerPage() == 0) {
		$pager = $pager;
	}
	else {
		$pager = $pager + 1;
	}
?>
<div class="testimonial testimonial-list-view">
<?php $count = 0; ?>
<?php foreach($testimonials as $testimonial): ?>
	<?php $testimonial = Mage::getModel('testimonial/testimonial')->load($testimonial); ?>
	<div class="item">
		<div class="avatar">
			<img class="img-responsive" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'testimonial/'. $testimonial->getAvatar();  ?>" alt="<?php $testimonial->getName(); ?>" />
		</div>
		<div class="content">
			<p class="name pull-left"><?php echo $testimonial->getName(); ?></p>
			<p class="information pull-right h6"><?php echo $testimonial->getInformation(); ?></p>
			<div class="clear"></div>
			<div class="comment"><?php echo $testimonial->getContent(); ?></div>
		</div>
	</div>
<?php endforeach; ?>
</div>
<div class="pager">
	<?php $this->getPageNumber($pager); ?>
</div>
