<?php

/* * ****************************************************
 * Package   : Social
 * Author    : HIEPNH
 * Copyright : (c) 2014
 * ***************************************************** */
?>
<?php if($this->getTitle()): ?>
	<div class="carousel_wrapper facebook-title">
		<div class="title">
			<h2><?php echo $this->getTitle() ?></h2>
		</div>
	</div>
<?php endif ?>
<?php echo $this->getFacebookLikeBox(); ?>
