<?php $object = $this->helper('mpanel')->getPageObject() ?>
<div>
	<div class="col-md-12">
		<div class="form-horizontal row">
			<input type="hidden" name="<?php echo $object['type'] ?>" value="<?php echo $object['id'] ?>"/>
			<div class="form-group">
				<label class="col-sm-4 control-label" for="page_title"><?php echo $this->__('Page Title') ?></label>
				<div class="col-sm-6">
					<input type="text" id="page_title" class="form-control" name="title" value="<?php echo $object['page_title'] ?>"/>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-4 control-label" for="meta_keywords"><?php echo $this->__('Meta Keywords') ?></label>
				<div class="col-sm-6">
					<textarea id="meta_keywords" class="form-control" name="meta_keywords"><?php echo $object['meta_keywords'] ?></textarea>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-4 control-label" for="meta_description"><?php echo $this->__('Meta Description') ?></label>
				<div class="col-sm-6">
					<textarea id="meta_description" class="form-control" name="meta_description"><?php echo $object['meta_description'] ?></textarea>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-12">
		<button class="btn btn-primary" type="submit"><span><span><?php echo $this->__('Update') ?></span></span></button>
	</div>
</div>