<div class="title">
   <h2><?php echo Mage::helper('oscheckout')->__('Shipping Address') ?></h2>
</div>
<div class="checkbox" id="shipping:same_as_billing_hide">
	<label for="shipping:same_as_billing">
		<input type="checkbox" name="billing[use_for_shipping]" id="shipping:same_as_billing" value="1"<?php if (!$this->isCustomerLoggedIn()): ?> checked="checked"<?php endif; ?> title="<?php echo Mage::helper('oscheckout')->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" />
		<?php echo Mage::helper('oscheckout')->__('Ship to same Address') ?>
	</label>
</div>
<?php if ($this->customerHasAddresses()): ?>
	<div id="shipping-old-address-form" class="field">
		<label for="shipping-address-select"><?php echo Mage::helper('oscheckout')->__('Select a shipping address from your address book or enter a new address.') ?></label>
		<div class="input-box">
			<?php echo $this->getAddressesHtmlSelect('shipping') ?>
		</div>
	</div>
<?php endif ?>
<div id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
	<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
	<input type="hidden" name="hasaddress" value="<?php echo $this->customerHasAddresses(); ?>" id="shipping:has_addresss" />
	<div class="no-width">
		<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
	</div>
	<?php if(!Mage::getStoreConfig('oscheckout/display/company')):?>
		<label for="shipping:company"><?php echo Mage::helper('oscheckout')->__('Company') ?></label>
		<div class="input-box">
			<input type="text" placeholder="<?php echo Mage::helper('oscheckout')->__('Company');?>" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo Mage::helper('oscheckout')->__('Company') ?>" class="form-control input-text" onchange="shipping.setSameAsBilling(false);" />
		</div>
	<?php endif; ?>

	<?php if (false): ?>
		<label for="shipping:email" class="required"><?php echo Mage::helper('oscheckout')->__('Email Address') ?></label>
		<div class="input-box">
			<input type="text" name="shipping[email]" id="shipping:email" placeholder="<?php echo Mage::helper('oscheckout')->__('Email Address');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo Mage::helper('oscheckout')->__('Email Address') ?>" class="form-control input-text validate-email required-entry" />
		</div>
	<?php endif ?>
	<?php if(!Mage::getStoreConfig('oscheckout/display/telephone')):?>
		<label for="shipping:telephone" class="required"><?php echo Mage::helper('oscheckout')->__('Telephone') ?></label>
		<div class="input-box">
			<input type="text" name="shipping[telephone]" placeholder="<?php echo Mage::helper('oscheckout')->__('Telephone');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('oscheckout')->__('Telephone') ?>" class="form-control input-text required-entry" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
		</div>
	<?php endif ?>
	<?php if(!Mage::getStoreConfig('oscheckout/display/fax')):?>
		<label for="shipping:fax"><?php echo Mage::helper('oscheckout')->__('Fax') ?></label>
		<div class="input-box">
			<input type="text" name="shipping[fax]" placeholder="<?php echo Mage::helper('oscheckout')->__('Fax');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo Mage::helper('oscheckout')->__('Fax') ?>" class="form-control input-text" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
		</div>
	<?php endif; ?>
	<?php if(!Mage::getStoreConfig('oscheckout/display/address')):?>
		<label for="shipping:street1" class="required"> <?php echo Mage::helper('oscheckout')->__('Address') ?></label>
		<input type="text" title="<?php echo Mage::helper('oscheckout')->__('Street Address') ?>" placeholder="<?php echo Mage::helper('oscheckout')->__('Address #1');?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="form-control input-text required-entry" onchange="shipping.setSameAsBilling(false);" />
		<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
			<input type="text" title="<?php echo Mage::helper('oscheckout')->__('Street Address %s', $_i) ?>" placeholder="<?php echo Mage::helper('oscheckout')->__('Address #%s',$_i);?>" name="shipping[street][]" id="shipping:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="form-control input-text address-fields" onchange="shipping.setSameAsBilling(false);"/>
	   <?php endfor ?>
	<?php endif; ?>
	<label for="shipping:city" class="required"><?php echo Mage::helper('oscheckout')->__('City') ?></label>
	<div class="input-box">
		<input type="text" title="<?php echo Mage::helper('oscheckout')->__('City') ?>" name="shipping[city]" placeholder="<?php echo Mage::helper('oscheckout')->__('City');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="form-control input-text required-entry" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
	</div>
	<label for="shipping:region" class="required"><?php echo Mage::helper('oscheckout')->__('State/Province') ?></label>
	<div class="input-box">
		<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('oscheckout')->__('State/Province') ?>" class="form-control validate-select" style="display:none;">
			<option value=""><?php echo Mage::helper('oscheckout')->__('Please select region, state or province') ?></option>
		</select>
		<script type="text/javascript">
		//<![CDATA[
		$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
		//]]>
		</script>
		<input type="text" id="shipping:region" name="shipping[region]" placeholder="<?php echo Mage::helper('oscheckout')->__('State/Province');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('oscheckout')->__('State/Province') ?>" class="form-control input-text" style="display:none;" />
	</div>
	<label for="shipping:postcode" class="required"><?php echo Mage::helper('oscheckout')->__('Zip/Postal Code') ?></label>
	<div class="input-box">
		<input type="text" title="<?php echo Mage::helper('oscheckout')->__('Zip/Postal Code') ?>" placeholder="<?php echo Mage::helper('oscheckout')->__('Zip/Postal Code');?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="form-control input-text validate-zip-international required-entry" onchange="shipping.setSameAsBilling(false);" />
	</div>
	<label for="shipping:country_id" class="required"><?php echo Mage::helper('oscheckout')->__('Country') ?></label>
	<div class="input-box">
		<?php echo $this->getCountryHtmlSelect('shipping') ?>
	</div>
	<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
		<input type="hidden" name="shipping[save_in_address_book]" value="1" title="<?php echo Mage::helper('oscheckout')->__('Save in address book') ?>" id="shipping:save_in_address_book"  />
	<?php else: ?>
		<input type="hidden" name="shipping[save_in_address_book]" value="1" />
	<?php endif; ?>
</div>

<script type="text/javascript">
	//<![CDATA[
		$('shipping:country_id').addClassName('form-control');
		var shipping = new Shipping('oscheckout-form', '<?php echo $this->getUrl('checkout/onepage/saveShipping', array('_secure'=>true)) ?>','<?php echo $this->getUrl('checkout/onepage/shippingMethod', array('_secure'=>true)) ?>','<?php echo $this->getUrl('oscheckout/index/saveshippingmethod', array('_secure'=>true)) ?>');
		var shippingForm = new VarienForm('oscheckout-form');
		shipping.setSameAsBilling(true);
		shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
		$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
		<?php if(!Mage::getStoreConfig('oscheckout/display/state')):?>
			var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
		<?php endif; ?>
	//]]>
</script>