<?php if (($_products = $this->getSpecialProducts('featured')) && (count($_products)>0)): ?>
	<?php $helper = $this->helper('mpanel') ?>
	<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
	<?php 
		if(isset($_GET['perrow'])){
			$col = $_GET['perrow'];
		}else{
			if($this->getCountPerRow()){
				$col = $this->getCountPerRow();
			}
			else{
				$col = 3;
			}
		}
		$perrow = $col;
		$col = $helper->convertColRowCustom($col);
	?>
	<?php $i=0; foreach ($_products as $_product): $i++; ?>
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
		<?php $class = $helper->getItemClass($perrow, $i) ?>
		<li class="item <?php if($col !=''): ?>col-md-<?php echo $col; ?> col-sm-4 col-xs-12  col-xs-half<?php endif; ?><?php if($i % $perrow == 1): ?> first-row-item <?php endif ?><?php echo $class ?>">
			<div class="product-content">
				<div class="product-top">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
						<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
							alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
						<?php endif ?>
					</a>
					<?php echo $helper->getProductLabel($_product) ?>
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					
					<ul class="icon-links">
						<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
							<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-eye"></em></button></li>
						<?php endif ?>
						<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
							<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
						<?php endif; ?>
						<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
						<?php if($_compareUrl && $helper->isShowCompare()): ?>
							<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
						<?php endif; ?>
					</ul>
				</div>
				<div class="product-desc">
					<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
					<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
					<div class="controls">
					<?php if($helper->isShowAddtoCart()): ?>
						<div class="add-to-cart">
							<?php if ($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
							<?php else: ?>
								<p class="h6"><?php echo $this->__('Sold') ?></p>
							<?php endif; ?>
						</div>
					<?php endif ?>
					</div>
				</div>
			</div>
		</li>
	<?php endforeach ?>
<?php else: ?>		
	<div class="alert alert-danger no-product-display col-xs-12">
		<p><?php echo $this->__('There are no products matching the selection.') ?></p>
	</div>
<?php endif ?>