<?php 
	$categories = $this->getCategoryCollection();
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $helper->convertColRow($col);
?>
<?php if(count($categories)>0): ?>
	<div class="featured-category-products featured-category-products-tabs">
		<?php if($this->getTitle()!=''): ?>
			<div class="carousel_wrapper">
				<div class="title">
					<h2><?php echo $this->getTitle() ?></h2>
				</div>
			</div>
		<?php endif ?>
		<div class="tabs-container category-product-item">
			<ul class="nav nav-tabs tab-menu" role="tablist">
				<?php $i=0; foreach($categories as $_category): $i++; ?>										
					<li<?php if($i==1): ?> class="active"<?php endif ?> role="presentation">
						<a href="#section-flip-<?php echo $i ?>" aria-controls="tabs-1" role="tab" data-toggle="tab" aria-expanded="true" >
							<span><?php echo $_category->getName() ?></span>
						</a>
					</li>
				<?php endforeach ?>
			</ul>
			<div class="products tab-content">
				<?php $i=0; foreach($categories as $_category): $i++; ?>
					<?php $products = $this->getProductByCategory($_category) ?>
					<?php if(count($products)>0): ?>
						<div class="tab-pane<?php if($i==1): ?> active<?php endif ?>" id="<?php echo "section-flip-".$i ?>" role="tabpanel">
							<div class="row">
								<div class="products-grid owl-carousel products-carousel" id="category_products_slider_<?php echo $_category->getId();?>">
									<?php foreach($products as $_product): ?>
										<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
										<div class="item">
											<div class="product-content">
												<div class="product-top">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
														<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
													</a>
													<?php echo $helper->getProductLabel($_product) ?>
													<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
												</div>
												<div class="product-desc">
													<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h4>
													<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
													<div class="controls">
													<?php if($helper->isShowAddtoCart()): ?>
														<div class="add-to-cart">
															<?php if ($_product->isSaleable()): ?>
																<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-xs btn-primary" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add To Cart'); ?></button>
															<?php else: ?>
																<p><?php echo $this->__('Our of stock') ?></p>
															<?php endif; ?>
														</div>
													<?php endif ?>
														<ul class="icon-links">
														<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
															<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
														<?php endif ?>
														<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
															<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
														<?php endif; ?>
														<?php if($_compareUrl=$this->getAddToCompareUrl($_product) && $helper->isShowCompare()): ?>
															<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
														<?php endif; ?>
														</ul>
													</div>
												</div>
											</div>     
										</div>
									<?php endforeach ?>
								</div>
							</div>
						</div>
						<script type="text/javascript">
							initSlider('category_products_slider_<?php echo $_category->getId() ?>', <?php echo $this->getColumn() ?>,false,false,true,false);
						</script>
					<?php else: ?>
						<div class="alert alert-danger">
							<p><?php echo $this->__('There are no products matching the selection.') ?></p>
						</div>
					<?php endif ?>
				<?php endforeach ?>
			</div>
		</div>
	</div>
<?php else: ?>
	<div class="alert alert-danger">
		<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
	</div>
<?php endif ?>