<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>
<?php if($this->getTitle()!=''): ?>
	<div class="carousel_wrapper">
		<div class="title">
			<h2><?php echo $this->getTitle() ?></h2>
		</div>
	</div>
<?php endif ?>

<?php //if(Mage::getStoreConfig('mpanel/catalog/featured')!=''): ?>
	<?php if(count($categories)>0): ?>
		<div class="featured-category-products">
			<?php foreach($categories as $_category): ?>
				<div class="row category-product-item">
					<div class="col-md-12"<?php if ($_imgUrl = $_category->getImageUrl()): ?> style="background:url('<?php echo $_imgUrl ?>') left top no-repeat"<?php endif ?>>
						<div class="row">
							<div class="col-md-3 col-sm-12 col-xs-12">
								<h3><?php echo $_category->getName() ?></h3>
								<div class="product-count"><?php echo $this->__('%s Items',$_category->getProductCount()) ?></div>
								<div class="cat-button"><button class="btn btn-default" onclick="setLocation('<?php echo $_category->getUrl() ?>')"><?php echo $this->__('View All') ?></button></div>
							</div>
							
							<?php $products = $this->getProductByCategory($_category) ?>
							<?php if(count($products)>0): ?>
								<div class="col-md-9 col-sm-12 col-xs-12">
									<div class="row">
										<ul class="products-grid" >
											<?php foreach($products as $_product): ?>
												<?php //$_product = Mage::getModel('catalog/product')->load($_product) ?>
												<li class="item col-md-<?php echo $col ?> col-sm-<?php echo $col ?> col-xs-12">
													<div class="wrapper-item">
														<div class="product-info-box product-hover">
															<div class="image-container">
																<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
																	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
																	<span class="hover-display">&nbsp;</span>
																</a>
																<div class="actions">
																	<div class="buttons">
																		<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																			<button class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></button>
																		<?php endif ?>
																		
																		<ul class="add-to-links tooltip-links">
																			<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
																				<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist btn" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart"></i></a></li>
																			<?php endif; ?>
																			<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
																				<li><a href="<?php echo $_compareUrl ?>" class="link-compare btn" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></a></li>
																			<?php endif; ?>
																		</ul>
																	</div>
																</div>
																<?php //echo $panelHelper->getProductLabel($_product) ?>
															</div>
														</div>
														
													
													</div>
												</li>
											<?php endforeach ?>
										</ul>
									</div>
								</div>
							<?php endif ?>
						</div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	<?php else: ?>
		<div class="alert alert-danger">
			<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
		</div>
	<?php endif ?>