<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>
<?php //if(Mage::getStoreConfig('mpanel/catalog/featured')!=''): ?>
	<?php if(count($categories)>0): ?>
		<div class="featured-category-products featured-category-products-tabs">
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper">
					<div class="title">
						<h2><?php echo $this->getTitle() ?></h2>
					</div>
				</div>
			<?php endif ?>
			<div class="category-product-item">
				<div class="col-md-12" id="tab-background">
					<div class="row">
						<div id="category_product_tabs" class="tabs-container">
							<ul class="nav nav-tabs tab-menu" role="tablist">
								<?php $i=0; foreach($categories as $_category): $i++; ?>										
									<li<?php if($i==1): ?> class="active"<?php endif ?> role="presentation">
										<a href="#section-flip-<?php echo $i ?>" aria-controls="tabs-1" role="tab" data-toggle="tab" aria-expanded="false" >
											<span><?php echo $_category->getName() ?></span>
											
										</a>
									</li>
								<?php endforeach ?>
							</ul>
							<div class="products tab-content">
										<?php $i=0; foreach($categories as $_category): $i++; ?>
											<?php $products = $this->getProductByCategory($_category) ?>
											<?php if(count($products)>0): ?>
												<div role="tabpanel" class="tab-pane<?php if($i==1): ?> active<?php endif ?>" id="<?php echo "section-flip-".$i ?>">
													<ul class="products-grid row" >
													<?php foreach($products as $_product): ?>
														<?php //$_product = Mage::getModel('catalog/product')->load($_product) ?>
														<li class="item col-md-<?php echo $col ?> col-sm-<?php echo $col ?> col-xs-12">
															<div class="product-content">
																<div class="product-top">
																	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
																			<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
																			
																	</a>
																	<?php echo $panelHelper->getProductLabel($_product) ?>
																	<div class="controls">
																		<ul class="icon-links">
																			
																		<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																			<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
																		<?php endif ?>
																		<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
									<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="window.location.href='<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>'"><em class="fa fa-heart-o"></em></button></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
									<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="window.location.href='<?php echo $_compareUrl ?>'"><em class="fa fa-retweet"></em></button></li>
								<?php endif; ?>
																		
																		</ul>
																	</div>
																	<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short');?>
																</div>
																<div class="product-desc">
																	<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></h2>
																	<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
																	<?php if ($_product->isSaleable()): ?>
																				<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-xs" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add To Cart') ?></button>
																			<?php endif; ?>
																</div>
																
															</div>
														</li>
													<?php endforeach ?>
												</ul>
												</div>
											<?php else: ?>
												<div class="alert alert-danger">
													<p><?php echo $this->__('There are no products matching the selection.') ?></p>
												</div>
											<?php endif ?>
										<?php endforeach ?>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	<?php else: ?>
		<div class="alert alert-danger">
			<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
		</div>
	<?php endif ?>
