<?php
/**
 * Octagono Ecommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 *
 *
 * @category   Cielo
 * @package    Octagono_Cielo
 * @copyright  Copyright (c) 2009-2011 - Octagono Ecommerce - www.octagonoecommerce.com.br
 * @license    http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 */
?>
<?php
$_code = $this->getMethodCode();
//feito para ter compatibilidade com o OneStepCheckout
$route = $this->getRequest()->getRequestedRouteName();
if ($route == 'onestepcheckout') {
    $fieldCode = '[' . $_code . ']';
} else {
    $fieldCode = '';
}
$cls = new Mage_Core_Model_Design_Package();
$path = $cls->getSkinBaseUrl();
$contaParcela = 1;
?>

<script type="text/javascript">
    function onCardChange(selectElement) {
        var selCard = selectElement.options[selectElement.selectedIndex].value;
        //alert(selCard);

        if (selCard == 'diners') {
            $('<?php echo $_code ?>_cc_number').setAttribute('maxlength', 14);
        }
        else {
            $('<?php echo $_code ?>_cc_number').setAttribute('maxlength', 16);
        }

        //quando um tipo de cartao e escolhida, limpa a escolha dos outros campos de tipo de cartao
        var results = $$('select');
        results.each(function (elem) {
            if (selectElement != elem && elem.id.indexOf('cc_type') > 0) {
                elem.value = '';
            }
        });
    }
    function mascara(o, f) {
        v_obj = o
        v_fun = f
        setTimeout("execmascara()", 1)
    }
    function execmascara() {
        v_obj.value = v_fun(v_obj.value)
    }
    function numeros(v) {
        v = v.replace(/\D/g, "")
        return v
    }
</script>
<div id="payment_form_<?php echo $_code ?>_cc" style="">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label><br />
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php //echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
            </div>
        </li>

        <?php $_ccType = $this->getInfoData('cc_type') ?>
        <?php $ccTypes = $this->getCcAvailableTypes(); ?>
        <li>
            <ul class="cards">
                <?php foreach ($ccTypes as $_typeCode => $_typeName): ?>
                    <li class="<?php echo strtolower(str_replace(' ', '_',$_typeName)); ?>" data-code="<?php echo $_typeCode; ?>"><?php echo $_typeName ?></li>
                <?php endforeach; ?>
                <input type="hidden" id="hiddenPayment" name="payment<?php echo $fieldCode; ?>[cc_type]" value="" />
            </ul>
        </li>
        
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label><br />
            <div class="input-box">
                <input  class="required-entry" type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" onkeyup="mascara(this, numeros)" onfocus="mascara(this, numeros)" onblur="mascara(this, numeros)" class="input-text" value="" maxlength="16" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label><br />
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                            <option value="<?php echo $v ? $v["label"] : '' ?>"<?php /*if ($k == $_ccExpMonth): ?> selected="selected"<?php endif */?>><?php echo $v['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                            <option value="<?php echo $k ? $k : '' ?>"<?php /*if ($k == $_ccExpYear): ?> selected="selected"<?php endif */?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <?php echo $this->getChildHtml() ?>
        <?php if ($this->hasVerification()): ?>
            <li>
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Código de Segurança') ?></label><br />
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" onkeyup="mascara(this, numeros)" onfocus="mascara(this, numeros)" onblur="mascara(this, numeros)" title="<?php echo $this->__('Código de Segurança') ?>" class="input-text cvv required-entry" size="5" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" maxlength="3" />
                    </div>                    
                </div>
            </li>
        <?php endif; ?>
        <li>
            <label for="<?php echo $_code ?>_parcelas"><?php echo $this->__('Parcelas') ?> </label><br />
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_parcelas" name="payment[cc_installments]">
                    <?php foreach($this->getInstallments() as $i => $installmentText): ?>
                        <option value="<?php echo $i; ?>"><?php echo $installmentText; ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
    </ul>
</div>
<br/>
<script type="text/javascript">
    jQuery(document).ready(function(){

        jQuery("#<?php echo $_code ?>_cc_number").keyup(function() {
            jQuery(".cards li").removeClass("on");
            vlInput = jQuery("#<?php echo $_code ?>_cc_number").val();
            regexVisa   = /^4[0-9]{12}(?:[0-9]{3})?/;
            regexMaster = /^5[1-5][0-9]{14}/;
            var regexAmex = /^3[47][0-9]{13}/;
            var regexDiners = /^3(?:0[0-5]|[68][0-9])[0-9]{11}/;
            var regexDiscover = /^6(?:011|5[0-9]{2})[0-9]{12}/;
            var regexJCB = /^(?:2131|1800|35\d{3})\d{11}/;
            var regexElo =/^((((636368)|(438935)|(504175)|(451416)|(636297))\d{0,10})|((509)|(5067)|(4576)|(4011))\d{0,12})$/;
            var regexHipercard   = /^(606282\d{10}(\d{3})?)|(3841\d{15})$/;

            if(regexVisa.test(vlInput)){
                jQuery(".cards li").removeClass("on");
                jQuery(".cards .visa").addClass("on");
                jQuery("#hiddenPayment").val('VI');
            }

            if(regexMaster.test(vlInput)){
                jQuery(".cards li").removeClass("on");
                jQuery(".cards .mastercard").addClass("on");
                jQuery("#hiddenPayment").val('MC');
            }


            if(regexElo.test(vlInput)){
                jQuery(".cards li").removeClass("on");
                jQuery(".cards .elo").addClass("on");
                jQuery("#hiddenPayment").val('EL');
            }

            if (regexDiners.test(vlInput)) {
                jQuery(".cards li").removeClass("on");
                jQuery(".cards .diners_club").addClass("on");
                jQuery("#hiddenPayment").val('DN');
            }
        });
    });
</script>
<style type="text/css">
    .tool-tip { 
        margin-left: 165px;
        margin-top: -250px;
        position: absolute;
    }
    .card-logo { }
    .card-logo li { float: left; text-align: center; margin-right: 15px !important;height:57px;vertical-align:bottom;display:block; position:relative; }
    .card-logo li .validation-advice {position:absolute;top:55px;width:150px}
    .payment-methods .form-list li .input-box .input-text.cvv { width:50px; margin-right:5px}
    .payment-methods .form-list li .input-box select { width:auto !important;margin-right:5px}


    .cards li {
        -webkit-transition: all .2s;
        -moz-transition: all .2s;
        -ms-transition: all .2s;
        -o-transition: all .2s;
        transition: all .2s;
        background-image: url('<?php echo $this->getSkinUrl('images/dutra_cielo/card.png');?>');
        background-position: 0 32px;
        display:inline-block;
        height:30px;
        margin-right: 8px;
        text-indent: -9999px;
        width:46px;
        cursor:pointer;
    }

    .cards .visa.on { background-position: 0px 0px; }
    .cards .american_express { background-position: 185px 32px; }
    .cards .american_express.on { background-position: 185px 0; }
    .cards .mastercard { background-position: 139px 32px; }
    .cards .mastercard.on { background-position: 139px 0px; }
    .cards .diners_club { background-position: 93px 32px; }
    .cards .diners_club.on { background-position: 93px 0px; }
    .cards .elo { background-position: 47px 32px; }
    .cards .elo.on { background-position:47px 0px; }

</style>