<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
if ($this->getTitle() != '') {
    $title = $this->getTitle();
} else {
    $title = 'Shop By';
}
?>
<?php if ($this->canShowBlock()): ?>
    <div
        class="block block-layered-nav<?php if (!$this->getLayer()->getState()->getFilters()): ?> block-layered-nav--no-filters<?php endif; ?>">
        <div class="block-title">
            <strong><span><?php echo $this->__($title) ?></span></strong>
        </div>
        <div class="block-content toggle-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a
                        href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
                <?php endif; ?>
                <?php if ($this->canShowOptions()): ?>
                <p class="block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php $attributeModel = $_filter->getAttributeModel(); ?>
                        <?php if ($attributeModel && $attributeModel->getAttributeCode() != '' && $attributeModel->getAttributeCode() != 'mgs_brand'): ?>
                            <?php if ($_filter->getItemsCount()): ?>
                                <dt><?php echo $this->__($_filter->getName()) ?></dt>
                                <dd><?php echo $_filter->getHtml() ?></dd>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>
    </div>
<?php else: ?>
    <?php if (Mage::helper('mpanel')->acceptToUsePanel()): ?>
        <div class="block block-layered-nav">
            <div class="block-title">
                <strong><span><?php echo $this->__($title) ?></span></strong>
            </div>
            <div class="block-content">
                <p><?php echo $this->__('Have no shopping options.'); ?></p>            
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>