<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
	<?php $widgetId = $this->getWidgetId();?>
	<?php $productCollection = $this->getProductCollection(); ?>
	<?php if(count($productCollection)>0): ?>
	
		<?php if($this->getTitle()!=''): ?>
			<div class="carousel_wrapper">
				<div class="title">
					<h2><?php echo $this->getTitle() ?></h2>
				</div>
			</div>
		<?php endif ?>

		<div id="deal_products" class="owl-carousel deal-carousel">
			<?php $i= 0; foreach($productCollection as $product): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
				<div class="item">
					<div class="product-info">
						<div class="product-image-container">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240); ?>" width="240" height="240" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							</a>
							<div class="discount-save">
								<div class="save-content">
									<?php echo $this->__('Save') ?>
									<div class="percent">
										<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
										<?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
										<?php echo $percent ?>%
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div class="slide-deals">
						<div class="deals-info">
							<div class="time-left">
								<div class="note"><?php echo $this->__('Time left') ?></div>
								<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->setData("widgetId", $widgetId)->toHtml(); ?>
							</div>
							<div class="item-info">
								<div class="sold">
									<?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
								</div>
								<div class="item-left">
									<?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
									<?php if($itemLeft!=''): ?>
										<?php if($itemLeft>1): ?>
											<?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
										<?php else: ?>
											<?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
										<?php endif ?>
									<?php else: ?>
										<?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
									<?php endif ?>
								</div>
							</div>
							<div class="addcart-button">
								<a href="<?php echo $this->getAddToCartUrl($_product) ?>"><span><?php echo $this->__('Buy Now') ?></span></a>
							</div>
						</div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
		
		<script type="text/javascript">
			initSlider('deal_products', <?php echo $this->getColumn() ?>, <?php echo $this->getAutoPlay()?>, <?php echo $this->getStopHover()?>, <?php echo $this->getNavigation()?>, <?php echo $this->getPagination()?>);
		</script>
	<?php endif ?>
<?php endif ?>
