<?php 
	$categories = $this->getCategoryCollection();
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $helper->convertColRow($col);
?>
<?php if(count($categories)>0): ?>
	<div class="product-block-list">
		<div class="products list-content">
			<?php $i=0; foreach($categories as $_category): $i++; ?>
			<?php if($i > 1){ break; } ?>
			<?php $products = $this->getProductByCategory($_category) ?>
			<?php if(count($products)>0): ?>
				<div class="boxed-content padding30">
					<?php if($this->getTitle()!=''): ?>
						<div class="title-block">
							<h4><?php echo $this->getTitle() ?></h4>
						</div>
					<?php else: ?>
						<div class="title-block">
							<h4><?php echo $_category->getName() ?></h4>
						</div>
					<?php endif ?>
					<div class="row">
					<?php $i=0; foreach($products as $_product): $i++; ?>
						<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
							<div class="item col-md-12 col-sm-6 col-xs-12 col-sm-half <?php if($i % 2 == 1): ?>row-2sm-first row-2xs-first<?php endif ?>">
								<div class="product-content">
									<div class="product-left">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
										</a>
									</div>
									<div class="product-right">
										<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
										<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
										<ul class="icon-links">
											<?php if($helper->isShowAddtoCart()): ?>
												<li class="add-to-cart">
													<?php if ($_product->isSaleable()): ?>
														<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
													<?php else: ?>
														<p class="h6"><?php echo $this->__('Sold') ?></p>
													<?php endif; ?>
												</li>
											<?php endif ?>
											<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
												<li class="add-wishlist"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
											<?php endif; ?>
											<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
											<?php if($_compareUrl && $helper->isShowCompare()): ?>
												<li class="add-compare"><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
											<?php endif; ?>
											<li class="clear"></li>
										</ul>
									</div>
									<div class="clear"></div>
								</div>     
							</div>
						<?php endforeach ?>
						</div>
					<?php else: ?>
						<div class="alert alert-danger">
							<p><?php echo $this->__('There are no products matching the selection.') ?></p>
						</div>
					<?php endif ?>
				</div>
				<button class="btn btn-full btn-go-cate" onclick="setLocation('<?php echo $_category->getUrl() ?>')"><?php echo $this->__('View More') ?>&nbsp;&nbsp;<span class="fa fa-long-arrow-right"></span></button>
			<?php endforeach ?>
		</div>
	</div>
<?php else: ?>
	<div class="alert alert-danger">
		<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
	</div>
<?php endif ?>