<?php 
	$categories = $this->getCategoryCollection();
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 2;
	}
	$item_row = $col;
	$col = $helper->convertColRow($col);
?>
<?php if(count($categories)>0): ?>
	<div class="products-grid">
		<div class="products list-content sidebar-grid-product">
			<?php $i=0; foreach($categories as $_category): $i++; ?>
			<?php if($i > 1){ break; } ?>
			<?php $products = $this->getProductByCategory($_category) ?>
			<?php if(count($products)>0): ?>
				<div class="boxed-content padding30">
					<?php if($this->getTitle()!=''): ?>
						<div class="title-block">
							<h4><?php echo $this->getTitle() ?></h4>
						</div>
					<?php else: ?>
						<div class="title-block">
							<h4><?php echo $_category->getName() ?></h4>
						</div>
					<?php endif ?>
					<div class="row">
					<?php $i=0; foreach($products as $_product): $i++; ?>
						<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
							<div class="<?php if($j % $item_row == 1): ?>first-row-item<?php endif ?> <?php if($j % 2 == 1): ?>row-2sm-fist<?php endif ?> item col-md-<?php echo $col ?> col-sm-6 col-xs-6">
								<div class="product-content">
									<div class="product-top">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
										</a>
									</div>
									<div class="product-desc">
										<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
										<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
									</div>
								</div>     
							</div>
						<?php endforeach ?>
						</div>
					<?php else: ?>
						<div class="alert alert-danger">
							<p><?php echo $this->__('There are no products matching the selection.') ?></p>
						</div>
					<?php endif ?>
				</div>
				<button class="btn btn-full btn-go-cate" onclick="setLocation('<?php echo $_category->getUrl() ?>')"><?php echo $this->__('View More') ?>&nbsp;&nbsp;<span class="fa fa-long-arrow-right"></span></button>
			<?php endforeach ?>
		</div>
	</div>
<?php else: ?>
	<div class="alert alert-danger">
		<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
	</div>
<?php endif ?>