<?php 
	$categories = $this->getCategoryCollection();
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $helper->convertColRow($col);
?>
<?php if(count($categories)>0): ?>
	<?php if($this->getTitle()!=''): ?>
		<div class="carousel_wrapper">
			<div class="title-content">
				<h3><?php echo $this->getTitle() ?></h3>
			</div>
		</div>
	<?php endif ?>
	<div class="shop-by-categories">
		<?php $i=0; foreach($categories as $_category): $i++; ?>
			<div class="categories-list">
				<div class="title-block visible-xs">
					<h3><?php echo $_category->getName() ?></h3>
				</div>
				<?php $products = $this->getProductByCategory($_category) ?>
				<?php if(count($products)>0): ?>
					<div class="row">
						<div class="col-custom-md-20 col-sm-custom-3 col-sm-4 hidden-xs">
							<?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
							<div class="banner-categories">
								<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>catalog/category/<?php echo $_category->getThumbnail() ?>" alt="<?php echo $this->escapeHtml($_category->getName()) ?>" class="img-responsive"/>
								<div class="text-content button-text-colour-white">
									<div class="cate-name">
										<h3 class="name" style="margin: 0;"><?php echo $_category->getName(); ?></h3>
									</div>
									<button onclick="setLocation('<?php echo $_category->getUrl() ?>')" type="button" class="btn btn-default btn-lg">
										<?php echo __('View More') ?>
									</button>
								</div>
							</div>
						</div>
						<div class="col-custom-md-80 col-sm-custom-9 col-sm-8 col-xs-12">
							<div class="row row-custom">
								<div class="products-grid owl-carousel products-carousel" id="shop_by_category_<?php echo $_category->getId();?>">
									<?php foreach($products as $_product): ?>
										<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
										<div class="item">
											<div class="product-content">
												<div class="product-top">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
														<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
													<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
														<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
														alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
													<?php endif ?>
													</a>
													<?php echo $helper->getProductLabel($_product) ?>
													<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
													<ul class="icon-links">
													<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
														<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-eye"></em></button></li>
													<?php endif ?>
													<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
														<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
													<?php endif; ?>
													<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
													<?php if($_compareUrl && $helper->isShowCompare()): ?>
														<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
													<?php endif; ?>
													</ul>
												</div>
												<div class="product-desc">
													<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h6>
													<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
													<div class="controls">
													<?php if($helper->isShowAddtoCart()): ?>
														<div class="add-to-cart">
															<?php if ($_product->isSaleable()): ?>
																<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-xs btn-primary" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
															<?php else: ?>
																<p class="h6"><?php echo $this->__('Sold') ?></p>
															<?php endif; ?>
														</div>
													<?php endif ?>
													</div>
												</div>
											</div>     
										</div>
									<?php endforeach ?>
								</div>
							</div>
						</div>
					</div>
					<script type="text/javascript">
						initSliderShop('shop_by_category_<?php echo $_category->getId() ?>', <?php echo $this->getColumn() ?>,false,false,true,false,<?php echo $helper->rightToLeftOwl(); ?>);
					</script>
				<?php else: ?>
					<div class="alert alert-danger">
						<p><?php echo $this->__('There are no products matching the selection.') ?></p>
					</div>
				<?php endif ?>
			</div>
		<?php endforeach ?>
	</div>
<?php else: ?>
	<div class="alert alert-danger">
		<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
	</div>
<?php endif ?>