<?php
/**
 * Storelocator template for store view
 *
 * @author Magento
 */

/**
 * @var $this MGS_Storelocator_Block_View
 * @see MGS_Storelocator_Block_View
 */
?>
<?php $_storeView = $this->helper('mgs_storelocator')->getStoreViewInstance(); ?>

<div class="col-md-5">
	<div class="page-title">
		<h1><?php echo $this->escapeHtml($_storeView->getName()) ?></h1>
	</div>
	 <?php if ($imageUrl = $_storeView->getStoreLogo()): ?>
		<div class="store-image">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'mgs_storelocator/'.$_storeView->getStoreLogo() ?>" alt="<?php echo $this->escapeHtml($_storeView->getName()) ?>" title="<?php echo $this->escapeHtml($_storeView->getName()) ?>" class="img-responsive"/>
		</div>
	<?php endif ?>
	<div class="store-info-detail">
		<div class="row">
			<div class="col-sm-3"><?php echo $this->__('Address:') ?></div>
			<div class="col-sm-9"><?php echo $this->escapeHtml($_storeView->getStreetAddress()).' '.$this->escapeHtml(ucfirst($_storeView->getCity())).' '.$this->escapeHtml(ucfirst($_storeView->getState())).' '.$this->escapeHtml($_storeView->getZipcode()).' '.$_storeView->getCountry() ?> </div>
		</div>
		<?php if($_storeView->getPhone()): ?>
			<div class="row">
				<div class="col-sm-3"><?php echo $this->__('Phone:') ?></div>
				<div class="col-sm-9"><a href="tel:<?php echo $this->escapeHtml($_storeView->getPhone()) ?>"><?php echo $this->escapeHtml($_storeView->getPhone()) ?></a></div>
			</div>
		<?php endif; ?>
		
		<?php if($_storeView->getEmail()): ?>
			<div class="row">
				<div class="col-sm-3"><?php echo $this->__('Email:') ?></div>
				<div class="col-sm-9"><a href="mailto:<?php echo $this->escapeHtml($_storeView->getEmail()) ?>"><?php echo $this->escapeHtml($_storeView->getEmail()) ?></a></div>
			</div>
		<?php endif; ?>
		
		<?php if($_storeView->getFax()): ?>
			<div class="row">
				<div class="col-sm-3"><?php echo $this->__('Fax:') ?></div>
				<div class="col-sm-9"><?php echo $this->escapeHtml($_storeView->getFax()) ?></div>
			</div>
		<?php endif; ?>
		<?php if($_storeView->getUrl()): ?>
			<div class="row">
				<div class="col-sm-12"><a href="<?php echo $_storeView->getUrl() ?>"><?php echo $_storeView->getUrl() ?></a></div>
			</div>
		<?php endif; ?>
		
		<?php if($_storeView->getDescription()): ?>
			<div class="store-html-content store-description">
				<h2><?php echo $this->__('Store Information') ?></h2>
				<div class="content">
					<?php echo $_storeView->getDescription(); ?>
				</div>
			</div>
		<?php endif ?>
		
		<?php if($_storeView->getTradingHours()): ?>
			<div class="store-html-content store-opening-hours">
				<h2><?php echo $this->__('Opening Hours') ?></h2>
				<div class="content">
					<?php echo $_storeView->getTradingHours(); ?>
				</div>
			</div>
		<?php endif ?>
	</div>
</div>
<div class="col-md-7">
	<div id="map-detail"></div>
	<p class="back">
		<button onclick="setLocation('<?php echo $this->getBackUrl() ?>');" class="btn btn-primary" title="<?php echo $this->__('Back') ?>" type="button">
			<span><span><?php echo $this->__('Back') ?></span></span>
		</button>
	</p>
</div>
<?php 
//Get store google map related information
$storeName = $_storeView->getName();
$storeLat = $_storeView->getLatitude();
$storeLong = $_storeView->getLongitude();
$storeRadius = $this->getRadius($_storeView);
?>
<?php if($storeLat && $storeLong): ?>
<script>
    //<![CDATA[
    var storeLat = <?php echo $storeLat ;?>;
    var storeLong = <?php echo $storeLong ;?>;
    var storeRadius = <?php echo $storeRadius ;?>;
    var storeInfoText = '<div class="map-short-info"><h3><?php echo $storeName ; ?></h3><p><?php echo $_storeView->getStreetAddress() ?> <?php echo $_storeView->getCity() ?> <?php echo $_storeView->getState() ?> <?php echo $_storeView->getZipcode() ?> <?php echo $_storeView->getCountry() ?></p>';
    var googleMapDivId = 'map-detail';
    google.maps.event.addDomListener(window, 'load', initialize(storeLat, storeLong, storeRadius, storeInfoText, googleMapDivId));
      //]]>
</script>
<?php endif ?>