<?php
/* * ****************************************************
 * Package   : ProductQuestions
 * Author    : http://www.arrowhitech.com
 * Copyright : (c) 2013 - ArrowHiTech.Com
 * ***************************************************** */
?>
<form id="search-form" method="get" action="<?php echo Mage::helper('productquestions')->faqsPageUrl() ?>" method="get">
    <div class="fieldset">
		<div class="title-block">
			<h4><?php echo Mage::helper('productquestions')->__('Search') ?></h4>
		</div>
        <ul class="form-list">
            <li class="fields">
                <div class="field form-group">
                    <label for="query" class="required"><?php echo Mage::helper('productquestions')->__('Keyword') ?><em>*</em></label>
                    <div class="input-box">
                        <input name="query" id="query" title="<?php echo Mage::helper('productquestions')->__('Keyword') ?>" <?php if ($this->getRequest()->getParam('query')): ?>value="<?php echo $this->getRequest()->getParam('query'); ?>"<?php endif; ?> class="input-text required-entry form-control" type="text" />
                    </div>
                </div>               
            </li>                                
        </ul>        
    </div>
    <div class="buttons-set text-right">              
        <button type="submit" title="<?php echo Mage::helper('productquestions')->__('Search') ?>" class="button btn btn-lg btn-primary"><span><span><?php echo Mage::helper('productquestions')->__('Search') ?></span></span></button>        
    </div>
</form>
<script type="text/javascript">
    var searchForm = new VarienForm('search-form');
</script>
