<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <?php $helper = $this->helper('mpanel') ?>
    <?php $size = $helper->convertRatioToMinSize($this->getProductRatio()) ?>
    <?php $panelHelper = $this->helper('mpanel');
    $size = $panelHelper->convertRatioToMinSize();
    ?>
    <div class="block product-block-list new-list box-collateral">
		<?php if ($this->getTitle() != ''): ?>
            <div class="title-block">
                <h4><?php echo $this->getTitle() ?></h4>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php $i = 0; foreach ($_products as $_product):  ?>
			<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
				<div class="item">
				   <div class="product-content">
						<div class="product-left">
							<a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
								<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive" />
							</a>
						</div>
						<div class="product-right">
							<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a></h6>
							
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							
							<?php echo $this->getPriceHtml($_product, true) ?>
							
						</div>
						<div class="clear"></div>
					</div>
				</div>
			<?php endforeach ?>
        </div>
    </div>
    <?php else: ?>
    <div class="block product-list-block featured-list box-collateral">
    <?php if ($this->getTitle() != ''): ?>
		<div class="title-block">
			<h4><?php echo $this->getTitle() ?></h4>
		</div>
    <?php endif ?>
        <div class="block-content">
            <div class="alert alert-danger no-product-display">
                <p><?php echo $this->__('There are no products matching the selection.') ?></p>
            </div>
        </div>
    </div>
<?php endif; ?>