<?php $menu = Mage::getModel('portfolio/category')->getCollection(); ?>
<?php if($this->getRequest()->getParam('id')){
	$checkParam = true;
	$id_param = $this->getRequest()->getParam('id');
}else{
	$checkParam = false;
}
?>
<div class="product-tabs-list">
	<ul class="tab-menu tabs_categories_porfolio">
		<li><a class="button h6 <?php if(!$checkParam): ?>is-checked<?php endif ?>" data-filter=".item_all"><?php echo $this->__('All') ?></a></li>
	<?php $i=0; foreach( $menu as $_menu ): $i++; ?>
		<?php $id_get = $_menu->getId(); ?>
		<li><a class="button h6 <?php if($checkParam && $id_get == $id_param): ?>is-checked<?php endif ?>" data-filter=".item_<?php echo $_menu->getId() ?>"><?php echo $_menu->getCategoryName() ?></a></li>
	<?php endforeach ?>
	</ul>
</div>
<div class="tabs_categories_porfolio_content isotope row">
	<?php $portfolios_all = $this->getPortfolios(); ?>
	<?php if(count($portfolios_all)>0): ?>
		<div class="portfolio-grid">
			<?php $i=0; foreach($portfolios_all as $portfolio_item): $i++; ?>
				<div class="item item_all col-md-4 col-sm-6 col-xs-12">
					<div class="portfolio-top-content">
						<a href="<?php echo $portfolio_item->getAddress(); ?>"><img src="<?php echo $this->helper('portfolio')->getThumbnail($portfolio_item)?>" alt="" class="img-responsive"/></a>
						<?php if($portfolio_item->getServices() != ''): ?>
							<span class="hover-info text-center text-colour-white button-text-colour-white">
								<span class="project h4"><?php echo $portfolio_item->getServices() ?></span>
							</span>
						<?php endif ?>
					</div>
					<div class="portfolio-bottom-content">
						<h4><a href="<?php echo $portfolio_item->getAddress(); ?>"><?php echo $portfolio_item->getName() ?></a></h4>
						<p class="category-link"><?php echo $this->helper('portfolio')->getCategoriesLink($portfolio_item)?></p>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	<?php else: ?>
		<div class="row">
			<div class="alert alert-danger item col-xs-12 item_all" style="min-height: 40px;"><?php echo $this->__('There are no portfolios matching the selection.') ?></div>
		</div>
	<?php endif ?>
	<?php $i=0; foreach( $menu as $_menu ): $i++; ?>
		<?php $id = $_menu->getId(); ?> 
		<?php $portfolios = $this->getPortfoliosForCate($id); ?>
			<?php if(count($portfolios)>0): ?>
				<div class="portfolio-grid">
					<?php $i=0; foreach($portfolios as $portfolio): $i++; ?>
						<div class="item item_<?php echo $id ?> col-md-4 col-sm-6 col-xs-12">
							<div class="portfolio-top-content">
								<a href="<?php echo $portfolio->getAddress(); ?>"><img src="<?php echo $this->helper('portfolio')->getThumbnail($portfolio)?>" alt="" class="img-responsive"/></a>
								<?php if($portfolio->getServices() != ''): ?>
									<span class="hover-info text-center text-colour-white button-text-colour-white">
										<span class="project h4"><?php echo $portfolio->getServices() ?></span>
									</span>
								<?php endif ?>
							</div>
							<div class="portfolio-bottom-content">
								<h4><a href="<?php echo $portfolio->getAddress(); ?>"><?php echo $portfolio->getName() ?></a></h4>
								<p class="category-link"><?php echo $this->helper('portfolio')->getCategoriesLink($portfolio)?></p>
							</div>
						</div>
					<?php endforeach ?>
				</div>
			<?php else: ?>
			<div class="row">
				<div class="alert alert-danger item col-xs-12 item_<?php echo $id ?>" style="min-height: 40px;"><?php echo $this->__('There are no portfolios matching the selection.') ?></div>
			</div>
			<?php endif ?>
	<?php endforeach ?>
</div>
<script type="text/javascript">
	mgsjQuery(window).load(function() {
		var container = mgsjQuery('.isotope').isotope({
			itemSelector: '.item',
			layoutMode: 'fitRows',
			getSortData: {
				name: '.item'
			}
		});
		mgsjQuery('.tabs_categories_porfolio').each( function( i, buttonGroup ) {
			var filterLoadValue = mgsjQuery(this).find('.is-checked').attr('data-filter');
			container.isotope({ filter: filterLoadValue });
		});
	});
	mgsjQuery(window).ready(function() {
		var container = mgsjQuery('.isotope').isotope({
			itemSelector: '.item',
			layoutMode: 'fitRows',
			getSortData: {
				name: '.item'
			}
		});
		mgsjQuery('.tabs_categories_porfolio').on( 'click', '.button', function() {
			var filterValue = mgsjQuery(this).attr('data-filter');
			container.isotope({ filter: filterValue });
		});
		mgsjQuery('.tabs_categories_porfolio').each( function( i, buttonGroup ) {
			var buttonGroup = mgsjQuery(buttonGroup);
			buttonGroup.on( 'click', '.button', function() {
				buttonGroup.find('.is-checked').removeClass('is-checked');
				mgsjQuery(this).addClass('is-checked');
			});
		});
	});
</script>