<?php
/**
 * @category    AM
 * @package     AM_RevSlider
 * @copyright   Copyright (C) 2008-2014 ArexMage.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      ArexMage.com
 * @email       support@arexmage.com
 */
?>
<?php
$element = $this->getElement();
$id = $element->getHtmlId();
?>
<tr>
    <td colspan="2">
        <div style="width: 100%">
            <textarea
                name="<?php echo $element->getName() ?>"
                id="<?php echo $id ?>"><?php echo $element->getValue() ?></textarea>
        </div>
    </td>
</tr>
<script type="text/javascript">
    var editor = $('<?php echo $id ?>');
    editor.up('table').setStyle({width:'100%'});
    CodeMirror && CodeMirror.fromTextArea(editor, {
        mode: '<?php echo $this->getData('mode') ?>',
        lineNumbers: true
    }).on('blur', function(instance){
        editor.value = instance.getValue();
    });
</script>
