<?php $portfolio = $this->getPortfolio() ?>
<div class="row portfolio-details">
	<div class="col-md-8 col-sm-7 col-xs-12">
		<div class="portfolio-image">
			<img src="<?php echo $this->helper('portfolio')->getBaseImage($portfolio)?>" alt="" class="img-responsive"/>
		</div>
	</div>
	
	<div class="col-md-4 col-sm-5 col-xs-12">
		<div class="portfolio-content">
			<h1><?php echo $portfolio->getName() ?></h1>
			<div class="description"><?php echo nl2br($portfolio->getDescription()) ?></div>
			<table class="table portfolio-table">
				<tbody>
					<?php if($portfolio->getPortfolioDate() != ''): ?>
						<tr>
							<td><?php echo $this->__('Date:') ?></td>
							<td><?php echo date('F d, Y', strtotime($portfolio->getPortfolioDate()))?></td>
						</tr>
					<?php endif ?>
					<?php if($portfolio->getServices() != ''): ?>
						<tr>
							<td><?php echo $this->__('Project:') ?></td>
							<td><a href="<?php echo $portfolio->getProjectUrl() ?>"><?php echo $portfolio->getServices() ?></a></td>
						</tr>
					<?php endif ?>
					<?php if($portfolio->getClient() != ''): ?>
						<tr>
							<td><?php echo $this->__('Client:') ?></td>
							<td><?php echo $portfolio->getClient() ?></td>
						</tr>
					<?php endif ?>
					<?php if($portfolio->getSkills() != ''): ?>
						<tr>
							<td><?php echo $this->__('Skills:') ?></td>
							<td><?php echo $portfolio->getSkills() ?></td>
						</tr>
					<?php endif ?>
					<?php if($this->helper('portfolio')->getCategoriesLink($portfolio) != ''): ?>
						<tr>
							<td><?php echo $this->__('Categories:') ?></td>
							<td><?php echo $this->helper('portfolio')->getCategoriesLink($portfolio) ?></td>
						</tr>
					<?php endif ?>
				</tbody>
			</table>
		</div>
	</div>
	
	<?php $relatedPortfolio = $this->helper('portfolio')->getRelatedPortfolio($portfolio) ?>
	<?php if(count($relatedPortfolio)>0): ?>
		<div class="portfolio-container col-md-12 col-sm-12 col-xs-12">
			<div class="block-title">
				<h3><?php echo $this->__('Projects') ?></h3>
			</div>
			<div class="owl-carousel portfolio-carousel" id="portfolio_carousel">
			<?php foreach($relatedPortfolio as $_portfolio): ?>
				<div class="item">

					<div class="portfolio-top-content">
						<a href="<?php echo $portfolio->getAddress(); ?>"><img src="<?php echo $this->helper('portfolio')->getThumbnail($_portfolio)?>" alt="" class="img-responsive"/></a>
						<span class="hover-info">
							<span class="fa fa-search"></span>
							<span class="project"><?php echo $_portfolio->getServices() ?></span>
							<span class="categories"><?php echo $this->helper('portfolio')->getCategoriesText($_portfolio)?></span>
						</span>
					</div>
					<div class="portfolio-bottom-content">
						<h4><a href="<?php echo $portfolio->getAddress(); ?>"><?php echo $_portfolio->getName() ?></a></h4>
						<p class="category-link"><?php echo $this->helper('portfolio')->getCategoriesLink($_portfolio)?></p>
					</div>
				</div>
			<?php endforeach ?>
			</div>
			

			<script type="text/javascript">
				initSlider('portfolio_carousel', 4, false, true, true, false);
			</script>
		</div>
	<?php endif ?>
</div>