<?php if (Mage::getStoreConfig('deals/general/enabled')): ?>
<?php
	$layout = Mage::getSingleton('core/layout');
	$productCollection = $this->getProductCollection();
	$toolbar = $this->getToolbarBlock();
	$pager = $layout->createBlock('page/html_pager');
	$toolbar->setChild('product_list_toolbar_pager', $pager);
	$toolbar->setCollection($productCollection);

	$toolbar->setMode($this->getMode());
	$toolbar->setTemplate('mgs/deals/toolbar.phtml');
?> 
<?php $helper = $this->helper('mpanel') ?>
<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
<div class="show-top">
	<?php echo $toolbar->toHtml(); ?>
</div>
<?php if (count($productCollection) > 0): ?>
	<div class="category-products">
        <?php if ($this->getMode() != 'grid'): ?>
            <ul class="deals-container deals-list">
                <?php foreach ($productCollection as $product): ?>
                    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                    <li class="deal-item">
						<div class="row">
							<div class="col-md-3 col-sm-4 col-xs-12">
								<div class="product-image">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
										<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									</a>
									<div class="discount-save">
										<div class="save-content">
											<?php echo $this->__('Save') ?>
											<div class="percent">
												<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
												<?php $percent = round(($save * 100) / $_product->getPrice(), 1) ?>
												<?php echo $percent ?>%
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-9 col-sm-8 col-xs-12">
								<h6 class="text-uppercase"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>" class="product-name"><?php echo $_product->getName() ?></a></h6>
									<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="deals-info">
									<div class="time-left">
										<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
									</div>
									<div class="short-description"><?php echo Mage::helper('core/string')->truncate($_product->getDescription(), 220); ?></div>
									<div class="item-info">
										<div class="sold">
											<?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
										</div>
										<div class="item-left">
												<?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
												<?php if ($itemLeft != ''): ?>
													<?php if ($itemLeft > 1): ?>
														<?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
													<?php else: ?>
														<?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
													<?php endif ?>
												<?php else: ?>
													<?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
												<?php endif ?>
											</div>
										</div>
										<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
											<input name="qty" type="text" class="input-text qty addcart-qty" id="addcartqty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" />
											<button class="button-addcart btn btn-primary btn-lg" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit();"><span><?php echo $this->__('Buy Now') ?></span></button>
										</form>
										<script type="text/javascript">
												var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
												productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function() {
													if (this.validator.validate()) {
														this.form.submit();
													}
												}.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
										</script>
									</div>
							</div>
						</div>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <?php $_collectionSize = $productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
			<ul class="products-grid row">
				<?php $i = 0; foreach ($productCollection as $product): $i++; ?>
				<?php $_product = Mage::getModel('catalog/product')->load($product->getId()); ?>
					<li class="col-md-4 col-sm-6 col-xs-12 col-sm-half item<?php if($i % 3 == 1): ?> first-row-item<?php endif ?><?php if($i % 2 == 1): ?> row-2-first<?php endif ?>">
						<div class="product-content">
							<div class="product-top">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
								<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
									<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
									alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
								<?php endif ?>
								</a>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short','') ?>
								<ul class="icon-links">
									<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
										<li><button type="button" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" class="link-wishlist"><em class="fa fa-heart"></em></button></li>
									<?php endif; ?>
									<?php $_compareUrl = $this->getAddToCompareUrl($_product); ?>
									<?php if ($_compareUrl && $helper->isShowCompare()): ?>
										<li><button type="button" onclick="setLocation('<?php echo $_compareUrl ?>')" class="link-compare">
											<em class="fa fa-retweet"></em></button></li>
									<?php endif; ?>
								</ul>
								<div class="deals-info">
									<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
								</div>
							</div>
							<div class="product-desc">
								<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?></a></h6>
								<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="controls">
									<div class="add-to-cart">
										<?php if ($_product->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><span class="fa fa-shopping-cart"></span></button>
										<?php else: ?>
											<p class="h6"><?php echo $this->__('Sold') ?></p>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach ?>
			</ul>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last']);</script>
        <?php endif; ?>
    <?php endif; ?>
	</div>
<div class="show-bottom">
    <?php echo $toolbar->toHtml();?>
</div>
<?php endif; ?>