<?php
/**
 * @name         :  MGS One Step Checkout
 * @version      :  1.4
 * @since        :  Magento ver 1.4, 1.5, 1.6, 1.7
 * @author       :  MGS - http://www.mage-shop.com
 * @copyright    :  Copyright (C) 2011 Powered by MGS
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  Sept 06 2012
 * 
 * */ ?>
<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table  class="cart_table table table-hover table-bordered" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
		<thead>
            <tr>
                <th><?php echo Mage::helper('oscheckout')->__('PRODUCT NAME') ?></th>
                <th class="a-center"><?php echo Mage::helper('oscheckout')->__('UNIT PRICE') ?></th>
                <th class="a-center"><?php echo Mage::helper('oscheckout')->__('QUANTITY') ?></th>
                <th class="a-center"><?php echo Mage::helper('oscheckout')->__('SUBTOTAL') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
				<tr>
					<th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
					<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
					<th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
					<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
				</tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>

