<?php $profile = $this->getProfile(); ?>
<div class="detail-profile">
	<div class="row">
		<div class="col-md-3 col-sm-4 col-xs-12 col-sm-half">
			<div class="user-wrapper">
				<div class="profile-image">
					<img alt="<?php echo $profile->getName(); ?>" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$profile->getPhoto() ?>">
				</div>
			</div>
		</div>
		<div class="col-md-9 col-sm-8 col-xs-12 col-sm-half">
			<div class="description">
				<span class="h3"><?php echo $profile->getName(); ?></span>
				<p class="information"><?php echo $profile->getDetail(); ?></p>
				<?php if($profile->getEmail() || $profile->getPosition() || $profile->getAddress()): ?>
					<table class="table">
						<tbody>
							<?php if($profile->getPosition()): ?>
								<tr>
									<td><?php echo $this->__('Position:') ?></td>
									<td><?php echo $profile->getPosition(); ?></td>
								</tr>
							<?php endif; ?>
							<?php if($profile->getEmail()): ?>
								<tr>
									<td><?php echo $this->__('Email:') ?></td>
									<td><?php echo $profile->getEmail(); ?></td>
								</tr>
							<?php endif; ?>
							<?php if($profile->getAddress()): ?>
								<tr>
									<td><?php echo $this->__('Address:') ?></td>
									<td><?php echo $profile->getAddress(); ?></td>
								</tr>
							<?php endif; ?>
						</tbody>
					</table>
				<?php endif ?>
				<?php if($profile->getFacebook()): ?>
					<a class="btn btn-profile btn-facebook" href="<?php echo $profile->getFacebook(); ?>"><i class="fa fa-facebook"></i></a>
				<?php endif ?>
				<?php if($profile->getGooglePlus()): ?>
					<a class="btn btn-profile btn-google" href="<?php echo $profile->getGooglePlus(); ?>"><i class="fa fa-google-plus"></i></a>
				<?php endif ?>
				<?php if($profile->getTwitter()): ?>
					<a class="btn btn-profile btn-twitter" href="<?php echo $profile->getTwitter(); ?>"><i class="fa fa-twitter"></i></a>
				<?php endif ?>
				<?php if($profile->getLinkedin()): ?>
					<a class="btn btn-profile btn-linkedin" href="<?php echo $profile->getLinkedin(); ?>"><i class="fa fa-linkedin"></i></a>
				<?php endif ?>
				<?php if($profile->getInstagram()): ?>
					<a class="btn btn-profile btn-instagram" href="<?php echo $profile->getInstagram(); ?>"><i class="fa fa-instagram"></i></a>
				<?php endif ?>
			</div>
		</div>
	</div>
</div>