<?php $template = $this->getRequest()->getParam('template') ?>
<?php $block = $this->getRequest()->getParam('block') ?>

<?php
	$exist = 0;
	if($id = $this->getRequest()->getParam('id')){
		$child =  Mage::getModel('mpanel/childs')->load($id);
		$exist = 1;
		$settings = json_decode($child->getSetting(), true);
		if(!isset($settings['count_per_row'])){
			$settings['count_per_row'] = 3;
		}
		
		if(!isset($settings['show_type'])){
			$settings['show_type'] = 'featured';
		}
	}
?>
<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/cat-tree.css') ?>" media="all" />
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ajax.js') ?>"></script>
		<?php $category = Mage::getModel('catalog/category')->load(Mage::app()->getStore($this->getRequest()->getParam('store'))->getRootCategoryId()); ?>
		<div class="edit-static-form">
			
			<form id="edit_form" method="post" action="<?php echo $this->getUrl('mpanel/post/child') ?>">
				<div class="row">
					<div class="col-md-12 builder-title">
						<h2><?php echo $this->__('Category Product Block');  ?></h2>
					</div>
				</div>
				
				<div class="form-horizontal">
					<input type="hidden" value="category_products" name="type" id="block_type"/>
					<input type="hidden" value="<?php echo $template ?>" name="home_name" id="block_home_name"/>
					<input type="hidden" value="<?php echo $block ?>" name="block_name" id="block_block_name"/>
					<?php if($exist): ?>
						<input type="hidden" value="<?php echo $child->getId() ?>" name="child_id" />
					<?php endif ?>
					
					<div id="form_tabs" class="tabbable">
						<ul class="nav nav-tabs">
							<li class="active">
								<a href="#general" data-toggle="tab">
									<?php echo $this->__('General') ?>
								</a>
							</li>
							
							<li>
								<a href="#product" data-toggle="tab" id="product-tab-nav">
									<?php echo $this->__('Category Config') ?>
								</a>
							</li>
							
							<li>
								<a href="#color" data-toggle="tab">
									<?php echo $this->__('Color') ?>
								</a>
							</li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="general">
								<div class="form-group">
									<label class="col-sm-4 control-label" for="col"><?php echo $this->__('Block col (12 to full)') ?></label>
									<div class="col-sm-8">
										<select name="col" class="required-entry input-text" id="col">
											<?php for($i=12; $i>=1; $i--): ?>
												<option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
											<?php endfor ?>
										</select>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="title"><?php echo $this->__('Title') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[title]" class="input-text" id="title"<?php if($exist): ?> value="<?php echo $settings['title'] ?>"<?php endif ?>/>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="custom_class"><?php echo $this->__('Custom Class') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[custom_class]" class="input-text" id="custom_class"<?php if($exist): ?> value="<?php echo $settings['custom_class'] ?>"<?php endif ?> />
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="animation"><?php echo $this->__('Block Animation') ?></label>
									<div class="col-sm-4">
										<select name="setting[animation]" class="input-text" id="animation" onchange="changeAnimationClass(this.value)">
											<?php $animation = $helper->getAnimationClass() ?>
											<?php foreach($animation as $_animate): ?>
												<option value="<?php echo $_animate['value'] ?>"<?php if($exist && ($settings['animation']==$_animate['value'])): ?> selected="selected"<?php endif ?>><?php echo $_animate['label'] ?></option>
											<?php endforeach ?>
										</select>
									</div>
									<div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test"><h1>Animation Preview</h1></div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="animation_delay"><?php echo $this->__('Animation Delay') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[animation_delay]" class="input-text validate-number" id="animation_delay" placeholder="ms" <?php if($exist && isset($settings['animation_delay'])): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>/>
									</div>
								</div>
							</div>
							
							<div class="tab-pane" id="product">
								<div class="form-group">
									<label class="col-sm-4 control-label" for="show_type"><?php echo $this->__('Show Products by') ?></label>
									<div class="col-sm-8">
										<select name="setting[show_type]" class="required-entry input-text" id="show_type">
											<option value="featured"<?php if($exist && ($settings['show_type']=='featured')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Featured Products') ?></option>
											<option value="new"<?php if($exist && ($settings['show_type']=='new')): ?> selected="selected"<?php endif ?>><?php echo $this->__('New Products') ?></option>
											<option value="position"<?php if($exist && ($settings['show_type']=='position')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Position') ?></option>
										</select>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="products_count"><?php echo $this->__('Number of Products per Category') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[products_count]" class="input-text required-entry" id="products_count"<?php if($exist): ?> value="<?php echo $settings['products_count'] ?>"<?php endif ?>/>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="count_per_row"><?php echo $this->__('Number of Products per row') ?></label>
									<div class="col-sm-8">
										<select name="setting[count_per_row]" class="required-entry input-text" id="count_per_row">
											<option value="1"<?php if($exist && ($settings['count_per_row']==1)): ?> selected="selected"<?php endif ?>>1</option>
											<option value="2"<?php if($exist && ($settings['count_per_row']==2)): ?> selected="selected"<?php endif ?>>2</option>
											<option value="3"<?php if($exist && ($settings['count_per_row']==3)): ?> selected="selected"<?php endif ?>>3</option>
											<option value="4"<?php if($exist && ($settings['count_per_row']==4)): ?> selected="selected"<?php endif ?>>4</option>
											<option value="5"<?php if($exist && ($settings['count_per_row']==5)): ?> selected="selected"<?php endif ?>>5</option>
											<option value="6"<?php if($exist && ($settings['count_per_row']==6)): ?> selected="selected"<?php endif ?>>6</option>
											<option value="7"<?php if($exist && ($settings['count_per_row']==7)): ?> selected="selected"<?php endif ?>>7</option>
											<option value="8"<?php if($exist && ($settings['count_per_row']==8)): ?> selected="selected"<?php endif ?>>8</option>
										</select>
									</div>
								</div>
								
								<?php $categoryProductLayout = $helper->getCategoryProductLayout();?>
								<?php if(count($categoryProductLayout)>0): ?>
									<?php
										if(!isset($settings['view_mode'])){
											$arrKey = array_keys($categoryProductLayout);
											$settings['view_mode'] = $arrKey[0];
										}
									?>
									<div class="form-group">
										<label class="col-sm-4 control-label" for="view_mode"><?php echo $this->__('Layout') ?></label>
										<div class="col-sm-8">
											<select name="setting[view_mode]" class="required-entry input-text" id="view_mode" onchange="changeViewMode(this.value)">
												<?php foreach($categoryProductLayout as $phtml =>$_layout): ?>
													<option value="<?php echo $phtml ?>"<?php if($exist && ($settings['view_mode']==$phtml)): ?> selected="selected"<?php endif ?>><?php echo $_layout ?></option>
												<?php endforeach ?>
											</select>
										</div>
									</div>
								<?php endif ?>
								
								<div class="form-group">
									<label class="col-sm-4 control-label"><?php echo $this->__('Category') ?></label>
									<div class="col-sm-8">
										<div id="product-categories" class="tree x-tree">
											<ul id="dhtmlgoodies_tree">
												<?php echo $helper->getTreeCategory($category,0) ?>
											</ul>
											<div id="expandCollapse">
												<a href="#" onclick="expandAll();return false"><?php echo $this->__('Expand all') ?></a>
												<a href="#" onclick="collapseAll();return false"><?php echo $this->__('Collapse all') ?></a>
											</div>
											<div id="ajaxMessage"></div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane" id="color">
								<div class="form-group text-color">
									<label class="col-sm-4 control-label" for="text_colour"><?php echo $this->__('Text colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[text_colour]" class="input-text" id="text_colour"<?php if($exist): ?> value="<?php echo $settings['text_colour'] ?>"<?php endif ?> readonly="true"/>
										
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('text_colour', this)"<?php if($settings['text_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#text-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="text-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['text_colour']!=''): ?>
											<?php echo $helper->getColorAccept('text_colour', $settings['text_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('text_colour'); ?>
										<?php endif ?>
										
										<a href="#" onclick="closeColorTable('#text-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group link-color">
									<label class="col-sm-4 control-label" for="link_colour"><?php echo $this->__('Link colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[link_colour]" class="input-text" id="link_colour"<?php if($exist): ?> value="<?php echo $settings['link_colour'] ?>"<?php endif ?> readonly="true"/>
										
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('link_colour', this)"<?php if($settings['link_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#link-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="link-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['link_colour']!=''): ?>
											<?php echo $helper->getColorAccept('link_colour', $settings['link_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('link_colour'); ?>
										<?php endif ?>
										
										<a href="#" onclick="closeColorTable('#link-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group link-hover-color">
									<label class="col-sm-4 control-label" for="link_hover_colour"><?php echo $this->__('Link hover colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[link_hover_colour]" class="input-text" id="link_hover_colour"<?php if($exist): ?> value="<?php echo $settings['link_hover_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('link_hover_colour', this)"<?php if($settings['link_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#link-hover-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="link-hover-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['link_hover_colour']!=''): ?>
											<?php echo $helper->getColorAccept('link_hover_colour', $settings['link_hover_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('link_hover_colour'); ?>
										<?php endif ?>
										
										<a href="#" onclick="closeColorTable('#link-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group button-color">
									<label class="col-sm-4 control-label" for="button_colour"><?php echo $this->__('Button colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[button_colour]" class="input-text" id="button_colour"<?php if($exist): ?> value="<?php echo $settings['button_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('button_colour', this)"<?php if($settings['button_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#button-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="button-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['button_colour']!=''): ?>
											<?php echo $helper->getColorAccept('button_colour', $settings['button_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('button_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#button-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group button-hover-color">
									<label class="col-sm-4 control-label" for="button_hover_colour"><?php echo $this->__('Button hover colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[button_hover_colour]" class="input-text" id="button_hover_colour"<?php if($exist): ?> value="<?php echo $settings['button_hover_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('button_hover_colour', this)"<?php if($settings['button_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#button-hover-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="button-hover-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['button_hover_colour']!=''): ?>
											<?php echo $helper->getColorAccept('button_hover_colour', $settings['button_hover_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('button_hover_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#button-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group button-text-color">
									<label class="col-sm-4 control-label" for="button_text_colour"><?php echo $this->__('Button text colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[button_text_colour]" class="input-text" id="button_text_colour"<?php if($exist): ?> value="<?php echo $settings['button_text_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('button_text_colour', this)"<?php if($settings['button_text_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#button-text-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="button-text-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['button_text_colour']!=''): ?>
											<?php echo $helper->getColorAccept('button_text_colour', $settings['button_text_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('button_text_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#button-text-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group button-text-hover-color">
									<label class="col-sm-4 control-label" for="button_text_hover_colour"><?php echo $this->__('Button text hover colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[button_text_hover_colour]" class="input-text" id="button_text_hover_colour"<?php if($exist): ?> value="<?php echo $settings['button_text_hover_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('button_text_hover_colour', this)"<?php if($settings['button_text_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#button-text-hover-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="button-text-hover-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['button_text_hover_colour']!=''): ?>
											<?php echo $helper->getColorAccept('button_text_hover_colour', $settings['button_text_hover_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('button_text_hover_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#button-text-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group button-border-color">
									<label class="col-sm-4 control-label" for="button_border_colour"><?php echo $this->__('Button border colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[button_border_colour]" class="input-text" id="button_border_colour"<?php if($exist): ?> value="<?php echo $settings['button_border_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('button_border_colour', this)"<?php if($settings['button_border_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#button-border-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="button-border-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['button_border_colour']!=''): ?>
											<?php echo $helper->getColorAccept('button_border_colour', $settings['button_border_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('button_border_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#button-border-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group button-border-hover-color">
									<label class="col-sm-4 control-label" for="button_border_hover_colour"><?php echo $this->__('Button border hover colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[button_border_hover_colour]" class="input-text" id="button_border_hover_colour"<?php if($exist): ?> value="<?php echo $settings['button_border_hover_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('button_border_hover_colour', this)"<?php if($settings['button_border_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#button-border-hover-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="button-border-hover-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['button_border_hover_colour']!=''): ?>
											<?php echo $helper->getColorAccept('button_border_hover_colour', $settings['button_border_hover_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('button_border_hover_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#button-border-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
								
								<div class="form-group price-color">
									<label class="col-sm-4 control-label" for="price_colour"><?php echo $this->__('Price colour') ?></label>
									<div class="col-sm-6 color-input">
										<input type="text" name="setting[price_colour]" class="input-text" id="price_colour"<?php if($exist): ?> value="<?php echo $settings['price_colour'] ?>"<?php endif ?> readonly="true"/>
										<a class="remove-color" title="<?php echo $this->__('Remove Colour') ?>" onclick="removeColor('price_colour', this)"<?php if($settings['price_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
									</div>
									<div class="col-sm-2">
										<label class="control-label"><a href="#" onclick="openColorTable('#price-colour-content'); return false"><?php echo $this->__('Change colour') ?></a></label>
									</div>
									<div id="price-colour-content" class="color-content" style="display:none">
										<?php if($exist && $settings['price_colour']!=''): ?>
											<?php echo $helper->getColorAccept('price_colour', $settings['price_colour']); ?>
										<?php else: ?>
											<?php echo $helper->getColorAccept('price_colour'); ?>
										<?php endif ?>
										<a href="#" onclick="closeColorTable('#price-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="form-group builder-action">
							<div class="col-md-12">
								<div class="buttons">
									<?php if(!$exist): ?>
										<button onclick="history.go(-1)" class="btn btn-back" type="button">
											<span><span><?php echo $this->__('Back') ?></span></span>
										</button>
									<?php endif ?>
									<button id="submit-button" onclick="updateForm.submit(this)" class="btn btn-primary" type="button">
										<span><span><?php echo $this->__('Submit') ?></span></span>
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('mgs/mpanel/form/script_action.phtml')->toHtml() ?>
	<script type="text/javascript">
		var currentAnimate = '';
		<?php if($exist): ?>
			currentAnimate = '<?php echo $settings['animation'] ?>';
		<?php endif ?>
		
		function changeAnimationClass(animate){
			if(currentAnimate!=''){
				mgsjQuery('#animation-test').removeClass(currentAnimate);
			}
			mgsjQuery('#animation-test').addClass(animate);
			currentAnimate = animate;
		}
		
		function toggleSliderSettings(val){
			if(val==1){
				$('slider-settings').show();
			}
			else{
				$('slider-settings').hide();
			}
			
			mgsjQuery('#loadmore-setting').toggle();
		}
		
		function checkMasonry(){
			if($('masonry').value == 1){
				$('slider-setting').hide();
				$('slider-settings').hide();
			}
			else{
				$('slider-setting').show();
				if($('slider').value == 1){
					$('slider-settings').show();
				}
				else{
					$('slider-settings').hide();
				}
			}
		}
		
		function changeViewMode(val){
			if(val=='simple'){
				$('masonry-setting').show();
				checkMasonry();
			}
			else{
				$('masonry-setting').hide();
				$('slider-setting').show();
				checkMasonry();
			}
		}
		
		var dhtmlgoodies_tree;
		var imageFolder = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/<?php echo Mage::getStoreConfig('mpanel/general/themepack') ?>/default/images/';	// Path to images
		var folderImage = 'folder-open.gif';
		var plusImage = 'elbow-end-plus.gif';
		var minusImage = 'elbow-end-minus.gif';
		var initExpandedNodes = '';	// Cookie - initially expanded nodes;
		var fileName = 'updateNode.php';	// External file called by AJAX	
		var timeoutEdit = 20;	// Lower value = shorter delay from mouse is pressed down to textbox appears.
		
		
		var ajax = new sack();
		
		
		function expandAll()
		{
			var menuItems = dhtmlgoodies_tree.getElementsByTagName('LI');
			for(var no=0;no<menuItems.length;no++){
				var subItems = menuItems[no].getElementsByTagName('UL');
				if(subItems.length>0 && subItems[0].style.display!='block'){
					showHideNode(false,menuItems[no].id.replace(/[^0-9]/g,''));
				}			
			}
		}
		
		function collapseAll()
		{
			var menuItems = dhtmlgoodies_tree.getElementsByTagName('LI');
			for(var no=0;no<menuItems.length;no++){
				var subItems = menuItems[no].getElementsByTagName('UL');
				if(subItems.length>0 && subItems[0].style.display=='block'){
					showHideNode(false,menuItems[no].id.replace(/[^0-9]/g,''));
				}			
			}		
		}
		
		
		function showHideNode(e,inputId)
		{
			if(inputId){
				if(!document.getElementById('dhtmlgoodies_treeNode'+inputId))return;
				thisNode = document.getElementById('dhtmlgoodies_treeNode'+inputId).getElementsByTagName('IMG')[0]; 
			}else {
				thisNode = this;
			}
			if(thisNode.style.visibility=='hidden')return;
			var parentNode = thisNode.parentNode;
			inputId = parentNode.id.replace(/[^0-9]/g,'');
			if(thisNode.src.indexOf('plus')>=0){
				thisNode.src = thisNode.src.replace('plus','minus');
				parentNode.getElementsByTagName('UL')[0].style.display='block';
				if(!initExpandedNodes)initExpandedNodes = ',';
				if(initExpandedNodes.indexOf(',' + inputId + ',')<0) initExpandedNodes = initExpandedNodes + inputId + ',';
				
			}else{
				thisNode.src = thisNode.src.replace('minus','plus');
				parentNode.getElementsByTagName('UL')[0].style.display='none';
				initExpandedNodes = initExpandedNodes.replace(',' + inputId,'');
			}	
		}

		function okToNavigate()
		{
			if(editCounter<10)return true;
			return false;		
		}
		
		var editCounter = -1;
		var editEl = false;
		
		function initEditLabel(){	}
		
		function startEditLabel(){}
		
		function showUpdate()
		{
			document.getElementById('ajaxMessage').innerHTML = ajax.response;
		}
		
		function hideEdit()
		{				
			var editObj = editEl.previousSibling;	
			if(editObj.value.length>0){
				editEl.innerHTML = editObj.value;	
				ajax.requestFile = fileName + '?updateNode='+editObj.id.replace(/[^0-9]/g,'') + '&newValue='+editObj.value;	// Specifying which file to get
				ajax.onCompletion = showUpdate;	// Specify function that will be executed after file has been found
				ajax.runAJAX();		// Execute AJAX function
							
			}
			editEl.style.display='inline';
			editObj.style.display='none';
			editEl = false;			
			editCounter=-1;
		}
		
		function mouseUpEvent()
		{
			editCounter=-1;		
		}
		
		function initTree()
		{
			dhtmlgoodies_tree = document.getElementById('dhtmlgoodies_tree');
			var menuItems = dhtmlgoodies_tree.getElementsByTagName('LI');	// Get an array of all menu items
			for(var no=0;no<menuItems.length;no++){
				var subItems = menuItems[no].getElementsByTagName('UL');
				var img = document.createElement('IMG');
				img.src = imageFolder + plusImage;
				img.onclick = showHideNode;
				if(subItems.length==0)img.style.visibility='hidden';
				var aTag = menuItems[no].getElementsByTagName('A')[0];
				
				if(aTag.id)numericId = aTag.id.replace(/[^0-9]/g,'');else numericId = (no+1);
				
				aTag.id = 'dhtmlgoodies_treeNodeLink' + numericId;
				
				var input = document.createElement('INPUT');
				input.style.width = '200px';
				input.style.display='none';
				menuItems[no].insertBefore(input,aTag);
				input.id = 'dhtmlgoodies_treeNodeInput' + numericId;
				input.onblur = hideEdit;
							
				menuItems[no].insertBefore(img,input);
				menuItems[no].id = 'dhtmlgoodies_treeNode' + numericId;
				aTag.onclick = okToNavigate;
				aTag.onmousedown = initEditLabel;
				var folderImg = document.createElement('IMG');
				if(menuItems[no].className){
					folderImg.src = imageFolder + menuItems[no].className;
				}else{
					folderImg.src = imageFolder + folderImage;
				}
				menuItems[no].insertBefore(folderImg,input);
			}	
			<?php if($exist && ($settings['category_id']!='')): ?>
				
				<?php 
					$arrId = array();
					foreach($settings['category_id'] as $catId){
						$cat = Mage::getModel('catalog/category')->load($catId);
						$arrId = array_unique(array_merge($arrId, $cat->getPathIds()));
					}
					$ids = implode(',',$arrId);
				?>
				initExpandedNodes = '<?php echo $ids ?>';
				 if(initExpandedNodes){
					var nodes = initExpandedNodes.split(',');
					for(var no=0;no<nodes.length;no++){
						if(nodes[no])showHideNode(false,nodes[no]);	
					}			
				}
			<?php endif ?>
			
			document.documentElement.onmouseup = mouseUpEvent;
		}
		
		window.onload = initTree;	
	</script>
<?php endif ?>