<?php $template = $this->getRequest()->getParam('template') ?>
<?php $block = $this->getRequest()->getParam('block') ?>

<?php 
	$exist = 0;
	if($id = $this->getRequest()->getParam('id')){
		$child =  Mage::getModel('mpanel/childs')->load($id);
		$exist = 1;
		
		$settings = json_decode($child->getSetting(), true);
	}
?>
<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
	
		<div class="edit-static-form">
			
			<form id="edit_form" method="post" action="<?php echo $this->getUrl('mpanel/post/child') ?>">
				<div class="row">
					<div class="col-md-12 builder-title">
						<h2><?php echo $this->__('Facebook Like Box Block') ?></h2>
					</div>
				</div>
				
				<div class="form-horizontal">
				
					<div id="form_tabs" class="tabbable">
						<ul class="nav nav-tabs">
							<li class="active">
								<a href="#general" data-toggle="tab">
									<?php echo $this->__('General') ?>
								</a>
							</li>
							
							<li>
								<a href="#product" data-toggle="tab" id="product-tab-nav">
									<?php echo $this->__('Facebook Config') ?>
								</a>
							</li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="general">
								<div class="form-group">
									<label class="col-sm-4 control-label" for="col"><?php echo $this->__('Block col (12 to full)') ?></label>
									<div class="col-sm-8">
										<select name="col" class="required-entry input-text" id="col">
											<?php for($i=12; $i>=1; $i--): ?>
												<option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
											<?php endfor ?>
										</select>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="title"><?php echo $this->__('Title') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[title]" class="input-text" id="title"<?php if($exist): ?> value="<?php echo $settings['title'] ?>"<?php endif ?> />
									</div>
								</div>
								
								<div class="form-group">
									<input type="hidden" value="facebook" name="type" id="block_type"/>
									<input type="hidden" value="<?php echo $template ?>" name="home_name" id="block_home_name"/>
									<input type="hidden" value="<?php echo $block ?>" name="block_name" id="block_block_name"/>
									<input type="hidden" name="current_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl() ?>"/>
									<?php if($exist): ?>
										<input type="hidden" value="<?php echo $child->getId() ?>" name="child_id" />
									<?php endif ?>
									
									<label class="col-sm-4 control-label" for="custom_class"><?php echo $this->__('Custom Class') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[custom_class]" class="input-text" id="custom_class"<?php if($exist): ?> value="<?php echo $settings['custom_class'] ?>"<?php endif ?> />
									</div>
									
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="animation"><?php echo $this->__('Block Animation') ?></label>
									<div class="col-sm-4">
										<select name="setting[animation]" class="input-text" id="animation" onchange="changeAnimationClass(this.value)">
											<?php $animation = $helper->getAnimationClass() ?>
											<?php foreach($animation as $_animate): ?>
												<option value="<?php echo $_animate['value'] ?>"<?php if($exist && ($settings['animation']==$_animate['value'])): ?> selected="selected"<?php endif ?>><?php echo $_animate['label'] ?></option>
											<?php endforeach ?>
										</select>
									</div>
									<div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test"><h1>Animation Preview</h1></div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-4 control-label" for="animation_delay"><?php echo $this->__('Animation Delay') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[animation_delay]" class="input-text validate-number" id="animation_delay" placeholder="ms" <?php if($exist && isset($settings['animation_delay'])): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>/>
									</div>
								</div>
							</div>
							
							<div class="tab-pane" id="product">
								<div class="form-group">
									<label class="col-sm-3 control-label" for="page_id"><?php echo $this->__('Page ID') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[page_id]" class="input-text required-entry" id="page_id" <?php if($exist && isset($settings['page_id'])): ?> value="<?php echo $settings['page_id'] ?>"<?php endif ?>/>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="width"><?php echo $this->__('Width') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[width]" class="input-text required-entry validate-number validate-greater-than-zero" id="width" <?php if($exist && isset($settings['width'])): ?> placeholder="<?php echo $this->__('The pixel width of the embed') ?>" value="<?php echo $settings['width'] ?>"<?php endif ?>/>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="height"><?php echo $this->__('Height') ?></label>
									<div class="col-sm-8">
										<input type="text" name="setting[height]" class="input-text required-entry validate-number validate-greater-than-zero" id="height" placeholder="<?php echo $this->__('The pixel height of the embed') ?>"<?php if($exist && isset($settings['height'])): ?> value="<?php echo $settings['height'] ?>"<?php endif ?>/>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="use_small_header"><?php echo $this->__('Use Small Header') ?></label>
									<div class="col-sm-8">
										<select name="setting[use_small_header]" class="input-text" id="use_small_header">
											<option value="0"><?php echo $this->__('No') ?></option>
											<option value="1"<?php if($exist && ($settings['use_small_header']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
										</select>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="data_adapt_container_width"><?php echo $this->__('Adapt to plugin container width') ?></label>
									<div class="col-sm-8">
										<select name="setting[data_adapt_container_width]" class="input-text" id="data_adapt_container_width">
											<option value="0"><?php echo $this->__('No') ?></option>
											<option value="1"<?php if($exist && ($settings['data_adapt_container_width']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
										</select>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="data_hide_cover"><?php echo $this->__('Hide Cover Photo') ?></label>
									<div class="col-sm-8">
										<select name="setting[data_hide_cover]" class="input-text" id="data_hide_cover">
											<option value="0"><?php echo $this->__('No') ?></option>
											<option value="1"<?php if($exist && ($settings['data_hide_cover']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
										</select>
									</div>
								</div>
								
								
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="data_show_facepile"><?php echo $this->__("Show Friend's Faces") ?></label>
									<div class="col-sm-8">
										<select name="setting[data_show_facepile]" class="input-text" id="data_show_facepile">
											<option value="0"><?php echo $this->__('No') ?></option>
											<option value="1"<?php if($exist && ($settings['data_show_facepile']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
										</select>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-sm-3 control-label" for="data_show_posts"><?php echo $this->__('Show Page Posts') ?></label>
									<div class="col-sm-8">
										<select name="setting[data_show_posts]" class="input-text" id="data_show_posts">
											<option value="0"><?php echo $this->__('No') ?></option>
											<option value="1"<?php if($exist && ($settings['data_show_posts']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
										</select>
									</div>
								</div>
							</div>
						</div>
					</div>
				
					<div class="row">
						<div class="form-group builder-action">
							<div class="col-md-12">
								<div class="buttons">
									<?php if(!$exist): ?>
										<button onclick="history.go(-1)" class="btn btn-back" type="button">
											<span><span><?php echo $this->__('Back') ?></span></span>
										</button>
									<?php endif ?>
									<button id="submit-button" onclick="updateForm.submit(this)" class="btn btn-primary" type="button">
										<span><span><?php echo $this->__('Submit') ?></span></span>
									</button>
								</div>
							</div>
						</div>
					</div>

				</div>
			</form>
		</div>
	<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('mgs/mpanel/form/script_action.phtml')->toHtml() ?>
	
	<script type="text/javascript">
		var updateForm = new VarienForm('edit_form');
		updateForm.submit = function(button, url) {
			if (this.validator.validate()) {
				mgsjQuery('#submit-button span span').html('<?php echo $this->__('Saving...') ?>');
				button.disabled = true;
				var form = this.form;
				var oldUrl = form.action;

				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					this.form.submit();
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}
				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(updateForm);
	</script>
<?php endif ?>

<?php if(Mage::getSingleton('core/session')->getSaved()==1): ?>
	<?php Mage::getSingleton('core/session')->setSaved(false); ?>
	
	<script type="text/javascript">
		if (window.parent == window.top) {
			parent.location.href=parent.location.href;
			window.parent.mgsjQuery.magnificPopup.close();
		}
	</script>
<?php endif ?>