<?php $template = $this->getRequest()->getParam('template') ?>
<?php $block = $this->getRequest()->getParam('block') ?>

<?php 
	$collection =  Mage::getModel('megamenu/parent')
		->getCollection()
		->addFieldToFilter('parent_id', array('neq'=>1))
		->addFieldToFilter('menu_type', 2)
		->addFieldToFilter('status', 1);

	$exist = 0;
	if($id = $this->getRequest()->getParam('id')){
		$child =  Mage::getModel('mpanel/childs')->load($id);
		$exist = 1;
		
		$settings = json_decode($child->getSetting(), true);
	}
?>
<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
	
		<div class="edit-static-form">
			
			<form id="edit_form" method="post" action="<?php echo $this->getUrl('mpanel/post/child') ?>">
				<div class="row">
					<div class="col-md-12 builder-title">
						<h2><?php echo $this->__('Megamenu Block') ?></h2>
					</div>
				</div>
				
				<div class="form-horizontal">
					<div class="row">
						<div class="form-group">
							<label class="col-sm-4 control-label" for="col"><?php echo $this->__('Block col (12 to full)') ?></label>
							<div class="col-sm-8">
								<select name="col" class="required-entry input-text" id="col">
									<?php for($i=12; $i>=1; $i--): ?>
										<option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
									<?php endfor ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<input type="hidden" value="megamenu" name="type" id="block_type"/>
							<input type="hidden" value="<?php echo $template ?>" name="home_name" id="block_home_name"/>
							<input type="hidden" value="<?php echo $block ?>" name="block_name" id="block_block_name"/>
							<input type="hidden" name="current_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl() ?>"/>
							<?php if($exist): ?>
								<input type="hidden" value="<?php echo $child->getId() ?>" name="child_id" />
							<?php endif ?>
							
							<label class="col-sm-4 control-label" for="menu_id"><?php echo $this->__('Menu') ?></label>
							
							<div class="col-sm-8">
								<select class="required-entry input-text" name="setting[menu_id]" id="menu_id">
									<option value=""></option>
									<?php if(count($collection)>0): ?>
										<?php foreach($collection as $menu): ?>
											<option value="<?php echo $menu->getId() ?>"<?php if($exist && ($settings['menu_id']==$menu->getId())): ?> selected="selected"<?php endif ?>><?php echo $menu->getTitle() ?></option>
										<?php endforeach ?>
									<?php endif ?>
								</select>
							</div>
							
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="custom_class"><?php echo $this->__('Custom Class') ?></label>
							<div class="col-sm-8">
								<input type="text" name="setting[custom_class]" class="input-text" id="custom_class"<?php if($exist): ?> value="<?php echo $settings['custom_class'] ?>"<?php endif ?> />
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="animation"><?php echo $this->__('Block Animation') ?></label>
							<div class="col-sm-4">
								<select name="setting[animation]" class="input-text" id="animation" onchange="changeAnimationClass(this.value)">
									<?php $animation = $helper->getAnimationClass() ?>
									<?php foreach($animation as $_animate): ?>
										<option value="<?php echo $_animate['value'] ?>"<?php if($exist && ($settings['animation']==$_animate['value'])): ?> selected="selected"<?php endif ?>><?php echo $_animate['label'] ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test"><h1>Animation Preview</h1></div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="animation_delay"><?php echo $this->__('Animation Delay') ?></label>
							<div class="col-sm-8">
								<input type="text" name="setting[animation_delay]" class="input-text validate-number" id="animation_delay" placeholder="ms" <?php if($exist && isset($settings['animation_delay'])): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>/>
							</div>
						</div>
						
						
						
						
						<div class="form-group builder-action">
							<div class="col-md-12">
								<div class="buttons">
									<?php if(!$exist): ?>
										<button onclick="history.go(-1)" class="btn btn-back" type="button">
											<span><span><?php echo $this->__('Back') ?></span></span>
										</button>
									<?php endif ?>
									<button id="submit-button" onclick="updateForm.submit(this)" class="btn btn-primary" type="button">
										<span><span><?php echo $this->__('Submit') ?></span></span>
									</button>
								</div>
							</div>
						</div>
					</div>

				</div>
			</form>
		</div>
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('mgs/mpanel/form/script_action.phtml')->toHtml() ?>
<?php endif ?>